# Generated by Django 4.2.29 on 2026-04-10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(db_index=True, max_length=36, unique=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            (
                                "needs_list_donation_export",
                                "Needs List Donation Export",
                            ),
                            (
                                "needs_list_procurement_export",
                                "Needs List Procurement Export",
                            ),
                        ],
                        db_index=True,
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("RETRYING", "Retrying"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor_user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150, null=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("tenant_code", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "source_resource_type",
                    models.CharField(
                        choices=[("NEEDS_LIST", "Needs List")],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("source_resource_id", models.CharField(db_index=True, max_length=100)),
                (
                    "source_snapshot_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "active_dedupe_key",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("artifact_filename", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "artifact_content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("artifact_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("artifact_payload", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "async_job",
            },
        ),
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(
                fields=["job_type", "status"], name="async_job_type_status"
            ),
        ),
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(
                fields=["source_resource_type", "source_resource_id"],
                name="async_job_source_lookup",
            ),
        ),
    ]
