from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_relief_management_backend_first"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationseligibilitydecision",
            old_name="relief_request_id",
            new_name="relief_request",
        ),
        migrations.RenameField(
            model_name="operationspackage",
            old_name="relief_request_id",
            new_name="relief_request",
        ),
        migrations.RenameField(
            model_name="operationspackagelock",
            old_name="package_id",
            new_name="package",
        ),
        migrations.RenameField(
            model_name="operationsdispatch",
            old_name="package_id",
            new_name="package",
        ),
        migrations.RenameField(
            model_name="operationsdispatchtransport",
            old_name="dispatch_id",
            new_name="dispatch",
        ),
        migrations.RenameField(
            model_name="operationswaybill",
            old_name="dispatch_id",
            new_name="dispatch",
        ),
        migrations.RenameField(
            model_name="operationsreceipt",
            old_name="dispatch_id",
            new_name="dispatch",
        ),
        migrations.RenameField(
            model_name="operationsreceipt",
            old_name="package_id",
            new_name="package",
        ),
        migrations.AlterField(
            model_name="operationseligibilitydecision",
            name="relief_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligibility_decision",
                to="operations.operationsreliefrequest",
            ),
        ),
        migrations.AlterField(
            model_name="operationspackage",
            name="relief_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="operations.operationsreliefrequest",
            ),
        ),
        migrations.AlterField(
            model_name="operationspackagelock",
            name="package",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lock_record",
                to="operations.operationspackage",
            ),
        ),
        migrations.AlterField(
            model_name="operationsdispatch",
            name="package",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatch_record",
                to="operations.operationspackage",
            ),
        ),
        migrations.AlterField(
            model_name="operationsdispatchtransport",
            name="dispatch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_record",
                to="operations.operationsdispatch",
            ),
        ),
        migrations.AlterField(
            model_name="operationswaybill",
            name="dispatch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waybills",
                to="operations.operationsdispatch",
            ),
        ),
        migrations.AlterField(
            model_name="operationsreceipt",
            name="dispatch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_record",
                to="operations.operationsdispatch",
            ),
        ),
        migrations.AlterField(
            model_name="operationsreceipt",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="operations.operationspackage",
            ),
        ),
        migrations.RemoveIndex(
            model_name="operationspackage",
            name="operations__relief__339193_idx",
        ),
        migrations.RemoveIndex(
            model_name="operationswaybill",
            name="operations__dispatc_f7d5ee_idx",
        ),
        migrations.AddIndex(
            model_name="operationspackage",
            index=models.Index(
                fields=["relief_request", "status_code"],
                name="operations__relief__339193_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operationswaybill",
            index=models.Index(
                fields=["dispatch", "generated_at"],
                name="operations__dispatc_f7d5ee_idx",
            ),
        ),
    ]
