# Generated by Django 4.2.27 on 2026-03-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_enforce_receipt_package_consistency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operationsreceipt',
            name='operations_receipt_unique_package',
        ),
        migrations.RemoveField(
            model_name='operationsreceipt',
            name='package',
        ),
    ]
