# Generated by Django 4.2.27 on 2026-03-31 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_remove_receipt_package_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsAllocationLine',
            fields=[
                ('create_by_id', models.CharField(max_length=50)),
                ('create_dtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by_id', models.CharField(max_length=50)),
                ('update_dtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_nbr', models.PositiveIntegerField(default=1)),
                ('line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('source_warehouse_id', models.IntegerField()),
                ('batch_id', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('source_type', models.CharField(default='ON_HAND', max_length=20)),
                ('source_record_id', models.IntegerField(blank=True, null=True)),
                ('uom_code', models.CharField(blank=True, max_length=25, null=True)),
                ('reason_text', models.CharField(blank=True, max_length=255, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_lines', to='operations.operationspackage')),
            ],
            options={
                'db_table': 'operations_allocation_line',
                'indexes': [models.Index(fields=['package', 'item_id'], name='operations__package_291cc8_idx'), models.Index(fields=['source_warehouse_id', 'item_id'], name='operations__source__7c20f2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='operationsallocationline',
            constraint=models.UniqueConstraint(fields=('package', 'source_warehouse_id', 'batch_id', 'item_id'), name='uq_ops_alloc_pkg_wh_batch_item'),
        ),
    ]
