# Generated by Django 4.2.27 on 2026-04-02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def add_transfer_context_column(apps, schema_editor) -> None:
    connection = schema_editor.connection
    if "transfer" not in connection.introspection.table_names():
        return
    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "transfer")
        }
    missing_columns = {
        "needs_list_id": "ALTER TABLE transfer ADD COLUMN needs_list_id INTEGER",
        "transfer_context": "ALTER TABLE transfer ADD COLUMN transfer_context VARCHAR(30)",
        "dispatched_at": "ALTER TABLE transfer ADD COLUMN dispatched_at TIMESTAMP WITH TIME ZONE",
        "dispatched_by": "ALTER TABLE transfer ADD COLUMN dispatched_by VARCHAR(20)",
        "expected_arrival": "ALTER TABLE transfer ADD COLUMN expected_arrival TIMESTAMP WITH TIME ZONE",
        "received_at": "ALTER TABLE transfer ADD COLUMN received_at TIMESTAMP WITH TIME ZONE",
        "received_by": "ALTER TABLE transfer ADD COLUMN received_by VARCHAR(20)",
    }
    for column_name, ddl in missing_columns.items():
        if column_name not in columns:
            schema_editor.execute(ddl)


def noop_reverse(apps, schema_editor) -> None:
    return


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0007_add_operations_allocation_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationspackage",
            name="consolidation_status",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="fulfillment_mode",
            field=models.CharField(default="DIRECT", max_length=40),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="partial_release_approval_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="partial_release_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="partial_release_approved_by_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="partial_release_request_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="partial_release_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="partial_release_requested_by_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="recommended_staging_warehouse_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="split_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="split_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="staging_override_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="staging_selection_basis",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="staging_warehouse_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspackage",
            name="split_from_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="split_children",
                to="operations.operationspackage",
            ),
        ),
        migrations.CreateModel(
            name="OperationsConsolidationLeg",
            fields=[
                ("create_by_id", models.CharField(max_length=50)),
                ("create_dtime", models.DateTimeField(default=django.utils.timezone.now)),
                ("update_by_id", models.CharField(max_length=50)),
                ("update_dtime", models.DateTimeField(default=django.utils.timezone.now)),
                ("version_nbr", models.PositiveIntegerField(default=1)),
                ("leg_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("leg_sequence", models.PositiveIntegerField()),
                ("source_warehouse_id", models.IntegerField()),
                ("staging_warehouse_id", models.IntegerField()),
                ("status_code", models.CharField(db_index=True, max_length=30)),
                ("shadow_transfer_id", models.IntegerField(blank=True, null=True)),
                ("driver_name", models.CharField(blank=True, max_length=120, null=True)),
                ("driver_license_no", models.CharField(blank=True, max_length=50, null=True)),
                ("vehicle_id", models.CharField(blank=True, max_length=50, null=True)),
                ("vehicle_registration", models.CharField(blank=True, max_length=50, null=True)),
                ("vehicle_type", models.CharField(blank=True, max_length=50, null=True)),
                ("transport_mode", models.CharField(blank=True, max_length=50, null=True)),
                ("transport_notes", models.TextField(blank=True, null=True)),
                ("dispatched_by_id", models.CharField(blank=True, max_length=50, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("expected_arrival_at", models.DateTimeField(blank=True, null=True)),
                ("received_by_user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("package", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consolidation_legs", to="operations.operationspackage")),
            ],
            options={
                "db_table": "operations_consolidation_leg",
            },
        ),
        migrations.AddConstraint(
            model_name="operationsconsolidationleg",
            constraint=models.UniqueConstraint(
                fields=("package", "leg_sequence"),
                name="uq_ops_consolidation_leg_package_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="operationsconsolidationleg",
            index=models.Index(fields=["package", "status_code"], name="ops_con_leg_pkg_status"),
        ),
        migrations.AddIndex(
            model_name="operationsconsolidationleg",
            index=models.Index(fields=["source_warehouse_id", "status_code"], name="ops_con_leg_src_status"),
        ),
        migrations.AddIndex(
            model_name="operationsconsolidationleg",
            index=models.Index(fields=["staging_warehouse_id", "status_code"], name="ops_con_leg_stage_status"),
        ),
        migrations.CreateModel(
            name="OperationsConsolidationLegItem",
            fields=[
                ("create_by_id", models.CharField(max_length=50)),
                ("create_dtime", models.DateTimeField(default=django.utils.timezone.now)),
                ("update_by_id", models.CharField(max_length=50)),
                ("update_dtime", models.DateTimeField(default=django.utils.timezone.now)),
                ("version_nbr", models.PositiveIntegerField(default=1)),
                ("leg_item_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_id", models.IntegerField()),
                ("batch_id", models.IntegerField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("source_type", models.CharField(default="ON_HAND", max_length=20)),
                ("source_record_id", models.IntegerField(blank=True, null=True)),
                ("staging_batch_id", models.IntegerField(blank=True, null=True)),
                ("uom_code", models.CharField(blank=True, max_length=25, null=True)),
                ("leg", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="operations.operationsconsolidationleg")),
            ],
            options={
                "db_table": "operations_consolidation_leg_item",
            },
        ),
        migrations.AddConstraint(
            model_name="operationsconsolidationlegitem",
            constraint=models.UniqueConstraint(
                fields=("leg", "item_id", "batch_id", "source_type"),
                name="uq_ops_consolidation_leg_item",
            ),
        ),
        migrations.AddIndex(
            model_name="operationsconsolidationlegitem",
            index=models.Index(fields=["leg", "item_id"], name="ops_con_leg_item_leg"),
        ),
        migrations.AddIndex(
            model_name="operationsconsolidationlegitem",
            index=models.Index(fields=["item_id", "batch_id"], name="ops_con_leg_item_batch"),
        ),
        migrations.CreateModel(
            name="OperationsConsolidationWaybill",
            fields=[
                ("waybill_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("waybill_no", models.CharField(max_length=50, unique=True)),
                ("artifact_payload_json", models.JSONField()),
                ("artifact_version", models.PositiveIntegerField(default=1)),
                ("generated_by_id", models.CharField(max_length=50)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_final_flag", models.BooleanField(default=True)),
                ("leg", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="waybills", to="operations.operationsconsolidationleg")),
            ],
            options={
                "db_table": "operations_consolidation_waybill",
            },
        ),
        migrations.AddIndex(
            model_name="operationsconsolidationwaybill",
            index=models.Index(fields=["leg", "generated_at"], name="ops_con_waybill_leg"),
        ),
        migrations.CreateModel(
            name="OperationsConsolidationReceipt",
            fields=[
                ("receipt_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("received_by_user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("received_by_name", models.CharField(blank=True, max_length=120, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_notes", models.TextField(blank=True, null=True)),
                ("receipt_artifact_json", models.JSONField(blank=True, null=True)),
                ("leg", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="receipt_record", to="operations.operationsconsolidationleg")),
            ],
            options={
                "db_table": "operations_consolidation_receipt",
            },
        ),
        migrations.CreateModel(
            name="OperationsPickupRelease",
            fields=[
                ("pickup_release_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("released_by_user_id", models.CharField(max_length=50)),
                ("released_by_name", models.CharField(blank=True, max_length=120, null=True)),
                ("released_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("release_notes", models.TextField(blank=True, null=True)),
                ("release_artifact_json", models.JSONField(blank=True, null=True)),
                ("package", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="pickup_release_record", to="operations.operationspackage")),
            ],
            options={
                "db_table": "operations_pickup_release",
            },
        ),
        migrations.RunPython(add_transfer_context_column, noop_reverse),
    ]
