# Generated by Django 4.2.27 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0008_staged_fulfillment"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationspickuprelease",
            name="collected_by_id_ref",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="operationspickuprelease",
            name="collected_by_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="operationspickuprelease",
            name="staging_warehouse_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationspickuprelease",
            name="tenant_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
