# Generated by Django 4.2.28 on 2026-03-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_ifrc_v3_generator_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemifrcsuggestlog',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'IFRC Suggest Log', 'verbose_name_plural': 'IFRC Suggest Logs'},
        ),
    ]
