from __future__ import annotations

import os
import re

from django.db import migrations


_FORWARD_SQL_TEMPLATE = """
CREATE TABLE IF NOT EXISTS "{schema}".ifrc_family (
    ifrc_family_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES "{schema}".itemcatg(category_id),
    group_code VARCHAR(4) NOT NULL,
    group_label VARCHAR(120) NOT NULL,
    family_code VARCHAR(6) NOT NULL,
    family_label VARCHAR(160) NOT NULL,
    source_version VARCHAR(80) NOT NULL,
    status_code CHAR(1) NOT NULL DEFAULT 'A',
    create_by_id VARCHAR(50) NOT NULL,
    create_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    update_by_id VARCHAR(50) NOT NULL,
    update_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    version_nbr INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_ifrc_family_group_family UNIQUE (group_code, family_code),
    CONSTRAINT c_ifrc_family_status CHECK (status_code IN ('A', 'I'))
);

CREATE INDEX IF NOT EXISTS idx_ifrc_family_category_status
    ON "{schema}".ifrc_family (category_id, status_code);

CREATE TABLE IF NOT EXISTS "{schema}".ifrc_item_reference (
    ifrc_item_ref_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ifrc_family_id BIGINT NOT NULL REFERENCES "{schema}".ifrc_family(ifrc_family_id),
    ifrc_code VARCHAR(30) NOT NULL,
    reference_desc VARCHAR(255) NOT NULL,
    category_code VARCHAR(6) NOT NULL,
    category_label VARCHAR(160) NOT NULL,
    spec_segment VARCHAR(7) NOT NULL DEFAULT '',
    source_version VARCHAR(80) NOT NULL,
    status_code CHAR(1) NOT NULL DEFAULT 'A',
    create_by_id VARCHAR(50) NOT NULL,
    create_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    update_by_id VARCHAR(50) NOT NULL,
    update_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    version_nbr INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_ifrc_item_reference_code UNIQUE (ifrc_code),
    CONSTRAINT uq_ifrc_item_reference_id_family UNIQUE (ifrc_item_ref_id, ifrc_family_id),
    CONSTRAINT c_ifrc_item_reference_status CHECK (status_code IN ('A', 'I'))
);

CREATE INDEX IF NOT EXISTS idx_ifrc_item_reference_family_status
    ON "{schema}".ifrc_item_reference (ifrc_family_id, status_code);

CREATE INDEX IF NOT EXISTS idx_ifrc_item_reference_code
    ON "{schema}".ifrc_item_reference (ifrc_code);

CREATE TABLE IF NOT EXISTS "{schema}".item_uom_option (
    item_uom_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL REFERENCES "{schema}".item(item_id) ON DELETE CASCADE,
    uom_code VARCHAR(25) NOT NULL REFERENCES "{schema}".unitofmeasure(uom_code),
    conversion_factor NUMERIC(18, 6) NOT NULL DEFAULT 1.0,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status_code CHAR(1) NOT NULL DEFAULT 'A',
    create_by_id VARCHAR(50) NOT NULL,
    create_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    update_by_id VARCHAR(50) NOT NULL,
    update_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    version_nbr INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uq_item_uom_option_item_uom UNIQUE (item_id, uom_code),
    CONSTRAINT c_item_uom_option_factor_positive CHECK (conversion_factor > 0),
    CONSTRAINT c_item_uom_option_status CHECK (status_code IN ('A', 'I')),
    CONSTRAINT c_item_uom_option_default_factor CHECK (
        (NOT is_default) OR conversion_factor = 1.0
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_item_uom_option_one_default
    ON "{schema}".item_uom_option (item_id)
    WHERE is_default = TRUE AND status_code = 'A';

CREATE TABLE IF NOT EXISTS "{schema}".item_classification_audit (
    item_classification_audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL REFERENCES "{schema}".item(item_id) ON DELETE CASCADE,
    change_action VARCHAR(32) NOT NULL,
    changed_fields_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    before_state_json JSONB,
    after_state_json JSONB NOT NULL,
    changed_by_id VARCHAR(50) NOT NULL,
    changed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_item_classification_audit_item_changed_at
    ON "{schema}".item_classification_audit (item_id, changed_at DESC);

CREATE OR REPLACE FUNCTION "{schema}".fn_prevent_item_classification_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'item_classification_audit is append-only';
END;
$$;

DROP TRIGGER IF EXISTS trg_item_classification_audit_no_mutation
    ON "{schema}".item_classification_audit;

CREATE TRIGGER trg_item_classification_audit_no_mutation
BEFORE UPDATE OR DELETE ON "{schema}".item_classification_audit
FOR EACH ROW
EXECUTE FUNCTION "{schema}".fn_prevent_item_classification_audit_mutation();

ALTER TABLE "{schema}".item
    ADD COLUMN IF NOT EXISTS ifrc_family_id BIGINT,
    ADD COLUMN IF NOT EXISTS ifrc_item_ref_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_item_ifrc_family_id
    ON "{schema}".item (ifrc_family_id);

CREATE INDEX IF NOT EXISTS idx_item_ifrc_item_ref_id
    ON "{schema}".item (ifrc_item_ref_id);

ALTER TABLE "{schema}".item
    DROP CONSTRAINT IF EXISTS fk_item_ifrc_family;

ALTER TABLE "{schema}".item
    ADD CONSTRAINT fk_item_ifrc_family
    FOREIGN KEY (ifrc_family_id)
    REFERENCES "{schema}".ifrc_family(ifrc_family_id);

ALTER TABLE "{schema}".item
    DROP CONSTRAINT IF EXISTS fk_item_ifrc_item_ref;

ALTER TABLE "{schema}".item
    ADD CONSTRAINT fk_item_ifrc_item_ref
    FOREIGN KEY (ifrc_item_ref_id)
    REFERENCES "{schema}".ifrc_item_reference(ifrc_item_ref_id);

ALTER TABLE "{schema}".item
    DROP CONSTRAINT IF EXISTS c_item_ifrc_ref_requires_family;

ALTER TABLE "{schema}".item
    ADD CONSTRAINT c_item_ifrc_ref_requires_family
    CHECK (ifrc_item_ref_id IS NULL OR ifrc_family_id IS NOT NULL);

ALTER TABLE "{schema}".item
    DROP CONSTRAINT IF EXISTS fk_item_ifrc_ref_family_match;

ALTER TABLE "{schema}".item
    ADD CONSTRAINT fk_item_ifrc_ref_family_match
    FOREIGN KEY (ifrc_item_ref_id, ifrc_family_id)
    REFERENCES "{schema}".ifrc_item_reference(ifrc_item_ref_id, ifrc_family_id)
    DEFERRABLE INITIALLY IMMEDIATE;
"""


_REVERSE_SQL_TEMPLATE = """
ALTER TABLE "{schema}".item
    DROP CONSTRAINT IF EXISTS fk_item_ifrc_ref_family_match;

ALTER TABLE "{schema}".item
    DROP CONSTRAINT IF EXISTS c_item_ifrc_ref_requires_family;

ALTER TABLE "{schema}".item
    DROP CONSTRAINT IF EXISTS fk_item_ifrc_item_ref;

ALTER TABLE "{schema}".item
    DROP CONSTRAINT IF EXISTS fk_item_ifrc_family;

DROP INDEX IF EXISTS "{schema}".idx_item_ifrc_item_ref_id;
DROP INDEX IF EXISTS "{schema}".idx_item_ifrc_family_id;

ALTER TABLE "{schema}".item
    DROP COLUMN IF EXISTS ifrc_item_ref_id,
    DROP COLUMN IF EXISTS ifrc_family_id;

DROP TRIGGER IF EXISTS trg_item_classification_audit_no_mutation
    ON "{schema}".item_classification_audit;

DROP FUNCTION IF EXISTS "{schema}".fn_prevent_item_classification_audit_mutation();

DROP TABLE IF EXISTS "{schema}".item_classification_audit;
DROP INDEX IF EXISTS "{schema}".ux_item_uom_option_one_default;
DROP TABLE IF EXISTS "{schema}".item_uom_option;
DROP TABLE IF EXISTS "{schema}".ifrc_item_reference;
DROP TABLE IF EXISTS "{schema}".ifrc_family;
"""


def _is_postgres(schema_editor) -> bool:
    return schema_editor.connection.vendor == "postgresql"


def _schema_name(schema_editor) -> str:
    configured = os.getenv("DMIS_DB_SCHEMA")
    if configured is not None:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", configured):
            raise RuntimeError(f"Invalid DMIS_DB_SCHEMA: {configured!r}")
        return configured

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT current_schema()")
        row = cursor.fetchone()
    return row[0] or "public"


def _quoted_schema_name(schema_editor) -> str:
    return f'"{_schema_name(schema_editor)}"'


def _legacy_item_table_exists(schema_editor) -> bool:
    relation = f"{_quoted_schema_name(schema_editor)}.item"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [relation])
        row = cursor.fetchone()
    return bool(row and row[0])


def _forwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    if not _legacy_item_table_exists(schema_editor):
        return

    schema = _schema_name(schema_editor)
    schema_editor.execute(_FORWARD_SQL_TEMPLATE.format(schema=schema))

    from masterdata.item_master_taxonomy import sync_item_master_taxonomy

    sync_item_master_taxonomy(schema_editor.connection, schema=schema)


def _backwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    if not _legacy_item_table_exists(schema_editor):
        return

    schema = _schema_name(schema_editor)
    schema_editor.execute(_REVERSE_SQL_TEMPLATE.format(schema=schema))


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ("masterdata", "0004_alter_itemifrcsuggestlog_options"),
    ]

    operations = [
        migrations.RunPython(_forwards, _backwards),
    ]
