from __future__ import annotations

import os
import re

from django.db import migrations


_FORWARD_SQL_TEMPLATE = """
CREATE TABLE IF NOT EXISTS {schema}.catalog_governance_audit (
    catalog_governance_audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_key VARCHAR(40) NOT NULL,
    record_pk BIGINT NOT NULL,
    change_action VARCHAR(32) NOT NULL,
    changed_fields_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    before_state_json JSONB,
    after_state_json JSONB NOT NULL,
    context_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    changed_by_id VARCHAR(50) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalog_governance_audit_lookup
    ON {schema}.catalog_governance_audit (table_key, record_pk, changed_at DESC);

CREATE OR REPLACE FUNCTION {schema}.fn_prevent_catalog_governance_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'catalog_governance_audit is append-only';
END;
$$;

DROP TRIGGER IF EXISTS trg_catalog_governance_audit_no_mutation
    ON {schema}.catalog_governance_audit;

CREATE TRIGGER trg_catalog_governance_audit_no_mutation
BEFORE UPDATE OR DELETE ON {schema}.catalog_governance_audit
FOR EACH ROW
EXECUTE FUNCTION {schema}.fn_prevent_catalog_governance_audit_mutation();
"""


_REVERSE_SQL_TEMPLATE = """
DROP TRIGGER IF EXISTS trg_catalog_governance_audit_no_mutation
    ON {schema}.catalog_governance_audit;

DROP FUNCTION IF EXISTS {schema}.fn_prevent_catalog_governance_audit_mutation();
DROP TABLE IF EXISTS {schema}.catalog_governance_audit;
"""


def _is_postgres(schema_editor) -> bool:
    return schema_editor.connection.vendor == "postgresql"


def _schema_name(schema_editor) -> str:
    configured = os.getenv("DMIS_DB_SCHEMA")
    if configured is not None:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", configured):
            raise RuntimeError(f"Invalid DMIS_DB_SCHEMA: {configured!r}")
        return configured

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT current_schema()")
        row = cursor.fetchone()
    return row[0] or "public"


def _relation_exists(schema_editor, relation_name: str) -> bool:
    relation = f"{_schema_name(schema_editor)}.{relation_name}"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [relation])
        row = cursor.fetchone()
    return bool(row and row[0])


def _forwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    if not _relation_exists(schema_editor, "ifrc_family"):
        return

    schema = _schema_name(schema_editor)
    schema_editor.execute(_FORWARD_SQL_TEMPLATE.format(schema=schema))


def _backwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    if not _relation_exists(schema_editor, "catalog_governance_audit"):
        return

    schema = _schema_name(schema_editor)
    schema_editor.execute(_REVERSE_SQL_TEMPLATE.format(schema=schema))


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ("masterdata", "0007_ifrc_reference_metadata_phase1"),
    ]

    operations = [
        migrations.RunPython(_forwards, _backwards),
    ]
