import os
import re

from django.db import migrations


_WAREHOUSE_FORWARD_SQL_TEMPLATE = """
ALTER TABLE "{schema}".warehouse
    ADD COLUMN IF NOT EXISTS parent_warehouse_id INTEGER;

CREATE INDEX IF NOT EXISTS idx_warehouse_parent_warehouse_id
    ON "{schema}".warehouse (parent_warehouse_id);

ALTER TABLE "{schema}".warehouse
    DROP CONSTRAINT IF EXISTS fk_warehouse_parent_warehouse;

ALTER TABLE "{schema}".warehouse
    ADD CONSTRAINT fk_warehouse_parent_warehouse
    FOREIGN KEY (parent_warehouse_id)
    REFERENCES "{schema}".warehouse(warehouse_id);

ALTER TABLE "{schema}".warehouse
    DROP CONSTRAINT IF EXISTS c_warehouse_parent_not_self;

ALTER TABLE "{schema}".warehouse
    ADD CONSTRAINT c_warehouse_parent_not_self
    CHECK (parent_warehouse_id IS NULL OR parent_warehouse_id <> warehouse_id);
"""


_STOCK_STATUS_FORWARD_SQL_TEMPLATE = """

DROP VIEW IF EXISTS "{schema}".v_stock_status;

CREATE VIEW "{schema}".v_stock_status AS
WITH stock_rows AS (
    SELECT
        w.warehouse_id,
        w.warehouse_name,
        w.warehouse_type,
        w.parent_warehouse_id,
        i.item_id,
        i.item_code,
        i.item_name,
        i.criticality_level,
        COALESCE(inv.usable_qty, 0::numeric) AS available_stock,
        COALESCE(inv.reserved_qty, 0::numeric) AS reserved_qty,
        COALESCE(
            NULLIF(inv.reorder_qty, 0::numeric),
            NULLIF(i.reorder_qty, 0::numeric),
            NULLIF(i.min_stock_threshold, 0::numeric),
            NULLIF(w.min_stock_threshold, 0::numeric),
            0::numeric
        ) AS reorder_level_qty,
        CASE
            WHEN COALESCE(NULLIF(inv.reorder_qty, 0::numeric), 0::numeric) > 0::numeric THEN 'INVENTORY'::text
            WHEN COALESCE(NULLIF(i.reorder_qty, 0::numeric), 0::numeric) > 0::numeric THEN 'ITEM'::text
            WHEN COALESCE(NULLIF(i.min_stock_threshold, 0::numeric), 0::numeric) > 0::numeric THEN 'ITEM_MIN'::text
            WHEN COALESCE(NULLIF(w.min_stock_threshold, 0::numeric), 0::numeric) > 0::numeric THEN 'WAREHOUSE_MIN'::text
            ELSE 'UNCONFIGURED'::text
        END AS reorder_level_source,
        COALESCE(i.min_stock_threshold, w.min_stock_threshold, 0::numeric) AS min_threshold,
        COALESCE(inv.usable_qty, 0::numeric) - COALESCE(i.min_stock_threshold, w.min_stock_threshold, 0::numeric) AS surplus_qty,
        w.last_sync_dtime,
        w.sync_status
    FROM "{schema}".warehouse w
    CROSS JOIN "{schema}".item i
    LEFT JOIN "{schema}".inventory inv
        ON inv.item_id = i.item_id
        AND inv.inventory_id = w.warehouse_id
    WHERE w.status_code = 'A'::bpchar
      AND i.status_code = 'A'::bpchar
)
SELECT
    stock_rows.warehouse_id,
    stock_rows.warehouse_name,
    stock_rows.warehouse_type,
    stock_rows.parent_warehouse_id,
    stock_rows.item_id,
    stock_rows.item_code,
    stock_rows.item_name,
    stock_rows.criticality_level,
    stock_rows.available_stock,
    stock_rows.reserved_qty,
    stock_rows.reorder_level_qty,
    stock_rows.reorder_level_source,
    stock_rows.min_threshold,
    stock_rows.surplus_qty,
    CASE
        WHEN stock_rows.reorder_level_source = 'UNCONFIGURED'::text THEN 'UNKNOWN'::text
        WHEN stock_rows.available_stock <= 0::numeric THEN 'RED'::text
        WHEN stock_rows.available_stock <= stock_rows.reorder_level_qty THEN 'AMBER'::text
        ELSE 'GREEN'::text
    END AS stock_health_status,
    stock_rows.last_sync_dtime,
    stock_rows.sync_status,
    CASE
        WHEN stock_rows.last_sync_dtime IS NULL THEN 'UNKNOWN'::text
        WHEN stock_rows.last_sync_dtime > (NOW() - INTERVAL '2 hours') THEN 'HIGH'::text
        WHEN stock_rows.last_sync_dtime > (NOW() - INTERVAL '6 hours') THEN 'MEDIUM'::text
        ELSE 'LOW'::text
    END AS data_freshness
FROM stock_rows;
"""


_REPACKAGING_FORWARD_SQL_TEMPLATE = """
CREATE TABLE IF NOT EXISTS "{schema}".uom_repackaging_txn (
    repackaging_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id INTEGER NOT NULL REFERENCES "{schema}".warehouse(warehouse_id),
    item_id INTEGER NOT NULL REFERENCES "{schema}".item(item_id),
    batch_id INTEGER NULL REFERENCES "{schema}".itembatch(batch_id),
    batch_no_snapshot VARCHAR(60) NULL,
    expiry_date_snapshot DATE NULL,
    source_uom_code VARCHAR(25) NOT NULL REFERENCES "{schema}".unitofmeasure(uom_code),
    target_uom_code VARCHAR(25) NOT NULL REFERENCES "{schema}".unitofmeasure(uom_code),
    source_qty NUMERIC(18, 6) NOT NULL,
    target_qty NUMERIC(18, 6) NOT NULL,
    equivalent_default_qty NUMERIC(18, 6) NOT NULL,
    source_conversion_factor NUMERIC(18, 6) NOT NULL,
    target_conversion_factor NUMERIC(18, 6) NOT NULL,
    reason_code VARCHAR(40) NOT NULL,
    note_text TEXT NULL,
    create_by_id VARCHAR(50) NOT NULL,
    create_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    update_by_id VARCHAR(50) NOT NULL,
    update_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    version_nbr INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT c_uom_repackaging_qty_positive CHECK (
        source_qty > 0
        AND target_qty > 0
        AND equivalent_default_qty > 0
        AND source_conversion_factor > 0
        AND target_conversion_factor > 0
    ),
    CONSTRAINT c_uom_repackaging_uoms_distinct CHECK (source_uom_code <> target_uom_code)
);

CREATE INDEX IF NOT EXISTS idx_uom_repackaging_txn_wh_item_created
    ON "{schema}".uom_repackaging_txn (warehouse_id, item_id, create_dtime DESC);

CREATE INDEX IF NOT EXISTS idx_uom_repackaging_txn_batch
    ON "{schema}".uom_repackaging_txn (batch_id);

CREATE TABLE IF NOT EXISTS "{schema}".uom_repackaging_audit (
    repackaging_audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repackaging_id BIGINT NOT NULL REFERENCES "{schema}".uom_repackaging_txn(repackaging_id) ON DELETE CASCADE,
    action_type VARCHAR(20) NOT NULL,
    before_state_json JSONB NULL,
    after_state_json JSONB NOT NULL,
    reason_code VARCHAR(40) NULL,
    note_text TEXT NULL,
    actor_id VARCHAR(50) NOT NULL,
    action_dtime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_uom_repackaging_audit_repackaging
    ON "{schema}".uom_repackaging_audit (repackaging_id, action_dtime DESC);

CREATE OR REPLACE FUNCTION "{schema}".fn_prevent_uom_repackaging_txn_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'uom_repackaging_txn is create-only';
END;
$$;

DROP TRIGGER IF EXISTS trg_uom_repackaging_txn_no_mutation
    ON "{schema}".uom_repackaging_txn;

CREATE TRIGGER trg_uom_repackaging_txn_no_mutation
BEFORE UPDATE OR DELETE ON "{schema}".uom_repackaging_txn
FOR EACH ROW
EXECUTE FUNCTION "{schema}".fn_prevent_uom_repackaging_txn_mutation();

CREATE OR REPLACE FUNCTION "{schema}".fn_prevent_uom_repackaging_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'uom_repackaging_audit is append-only';
END;
$$;

DROP TRIGGER IF EXISTS trg_uom_repackaging_audit_no_mutation
    ON "{schema}".uom_repackaging_audit;

CREATE TRIGGER trg_uom_repackaging_audit_no_mutation
BEFORE UPDATE OR DELETE ON "{schema}".uom_repackaging_audit
FOR EACH ROW
EXECUTE FUNCTION "{schema}".fn_prevent_uom_repackaging_audit_mutation();
"""


_WAREHOUSE_REVERSE_SQL_TEMPLATE = """
DROP VIEW IF EXISTS "{schema}".v_stock_status;

ALTER TABLE "{schema}".warehouse
    DROP CONSTRAINT IF EXISTS c_warehouse_parent_not_self;

ALTER TABLE "{schema}".warehouse
    DROP CONSTRAINT IF EXISTS fk_warehouse_parent_warehouse;

DROP INDEX IF EXISTS "{schema}".idx_warehouse_parent_warehouse_id;

ALTER TABLE "{schema}".warehouse
    DROP COLUMN IF EXISTS parent_warehouse_id;
"""


_STOCK_STATUS_REVERSE_SQL_TEMPLATE = """
CREATE VIEW "{schema}".v_stock_status AS
SELECT
    w.warehouse_id,
    w.warehouse_name,
    w.warehouse_type,
    i.item_id,
    i.item_code,
    i.item_name,
    i.criticality_level,
    COALESCE(inv.usable_qty, 0::numeric) AS available_stock,
    COALESCE(inv.reserved_qty, 0::numeric) AS reserved_qty,
    COALESCE(i.min_stock_threshold, w.min_stock_threshold, 0::numeric) AS min_threshold,
    COALESCE(inv.usable_qty, 0::numeric) - COALESCE(i.min_stock_threshold, w.min_stock_threshold, 0::numeric) AS surplus_qty,
    w.last_sync_dtime,
    w.sync_status,
    CASE
        WHEN w.last_sync_dtime IS NULL THEN 'UNKNOWN'::text
        WHEN w.last_sync_dtime > (NOW() - INTERVAL '2 hours') THEN 'HIGH'::text
        WHEN w.last_sync_dtime > (NOW() - INTERVAL '6 hours') THEN 'MEDIUM'::text
        ELSE 'LOW'::text
    END AS data_freshness
FROM "{schema}".warehouse w
CROSS JOIN "{schema}".item i
LEFT JOIN "{schema}".inventory inv
    ON inv.item_id = i.item_id
    AND inv.inventory_id = w.warehouse_id
WHERE w.status_code = 'A'::bpchar
  AND i.status_code = 'A'::bpchar;
"""


_REPACKAGING_REVERSE_SQL_TEMPLATE = """
DROP TABLE IF EXISTS "{schema}".uom_repackaging_audit;
DROP TABLE IF EXISTS "{schema}".uom_repackaging_txn;

DROP FUNCTION IF EXISTS "{schema}".fn_prevent_uom_repackaging_audit_mutation();
DROP FUNCTION IF EXISTS "{schema}".fn_prevent_uom_repackaging_txn_mutation();
"""


def _is_postgres(schema_editor) -> bool:
    return schema_editor.connection.vendor == "postgresql"


def _schema_name(schema_editor) -> str:
    configured = os.getenv("DMIS_DB_SCHEMA")
    if configured is not None:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", configured):
            raise RuntimeError(f"Invalid DMIS_DB_SCHEMA: {configured!r}")
        return configured

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT current_schema()")
        row = cursor.fetchone()
    return row[0] or "public"


def _relation_exists(schema_editor, relation: str) -> bool:
    schema = _schema_name(schema_editor)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = %s AND c.relname = %s
            LIMIT 1
            """,
            [schema, relation],
        )
        row = cursor.fetchone()
    return bool(row and row[0])


def _forwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    warehouse_relations = ("warehouse",)
    stock_status_relations = ("warehouse", "item", "inventory")
    repackaging_relations = ("warehouse", "item", "itembatch", "unitofmeasure")
    sql_parts: list[str] = []

    if all(_relation_exists(schema_editor, relation) for relation in warehouse_relations):
        sql_parts.append(_WAREHOUSE_FORWARD_SQL_TEMPLATE)
    if all(_relation_exists(schema_editor, relation) for relation in stock_status_relations):
        sql_parts.append(_STOCK_STATUS_FORWARD_SQL_TEMPLATE)
    if all(_relation_exists(schema_editor, relation) for relation in repackaging_relations):
        sql_parts.append(_REPACKAGING_FORWARD_SQL_TEMPLATE)
    if not sql_parts:
        return

    schema = _schema_name(schema_editor)
    schema_editor.execute("\n\n".join(sql_parts).format(schema=schema))


def _backwards(apps, schema_editor):
    if not _is_postgres(schema_editor):
        return
    warehouse_relations = ("warehouse",)
    stock_status_relations = ("warehouse", "item", "inventory")
    sql_parts: list[str] = [_REPACKAGING_REVERSE_SQL_TEMPLATE]
    if all(_relation_exists(schema_editor, relation) for relation in warehouse_relations):
        sql_parts.append(_WAREHOUSE_REVERSE_SQL_TEMPLATE)
    if all(_relation_exists(schema_editor, relation) for relation in stock_status_relations):
        sql_parts.append(_STOCK_STATUS_REVERSE_SQL_TEMPLATE)
    if not sql_parts:
        return

    schema = _schema_name(schema_editor)
    schema_editor.execute("\n\n".join(sql_parts).format(schema=schema))


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ("masterdata", "0008_catalog_governance_audit"),
    ]

    operations = [
        migrations.RunPython(_forwards, _backwards),
    ]
