# Generated by Django 4.2.27 on 2026-04-02

from collections import deque

from django.db import migrations, models


PARISH_CODES = (
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
)

PARISH_GRAPH = {
    "01": {"02", "14"},
    "02": {"01", "03", "04", "05", "14"},
    "03": {"02", "04"},
    "04": {"02", "03", "05"},
    "05": {"02", "04", "06"},
    "06": {"05", "07", "12", "14"},
    "07": {"06", "08", "12"},
    "08": {"07", "09", "11"},
    "09": {"08", "10"},
    "10": {"09", "11"},
    "11": {"08", "10", "12", "13"},
    "12": {"06", "07", "11", "13"},
    "13": {"11", "12", "14"},
    "14": {"01", "02", "06", "13"},
}


def _normalized_parish_graph() -> dict[str, set[str]]:
    normalized = {
        parish_code: set(PARISH_GRAPH.get(parish_code, ()))
        for parish_code in PARISH_CODES
    }
    for parish_code, neighbors in tuple(normalized.items()):
        for neighbor in tuple(neighbors):
            if neighbor not in normalized:
                continue
            normalized[neighbor].add(parish_code)
    return normalized


def _distance_map(source_code: str) -> dict[str, int]:
    graph = _normalized_parish_graph()
    queue = deque([(source_code, 0)])
    distances = {source_code: 0}
    while queue:
        current, distance = queue.popleft()
        for neighbor in sorted(graph.get(current, ())):
            if neighbor in distances:
                continue
            distances[neighbor] = distance + 1
            queue.append((neighbor, distance + 1))
    return distances


def seed_parish_proximity_matrix(apps, schema_editor) -> None:
    ParishProximityMatrix = apps.get_model("masterdata", "ParishProximityMatrix")
    rows = []
    for source_code in PARISH_CODES:
        distances = _distance_map(source_code)
        for candidate_code in PARISH_CODES:
            rows.append(
                ParishProximityMatrix(
                    source_parish_code=source_code,
                    candidate_parish_code=candidate_code,
                    proximity_rank=int(distances.get(candidate_code, 999)),
                )
            )
    ParishProximityMatrix.objects.bulk_create(rows, ignore_conflicts=True)


def unseed_parish_proximity_matrix(apps, schema_editor) -> None:
    ParishProximityMatrix = apps.get_model("masterdata", "ParishProximityMatrix")
    ParishProximityMatrix.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("masterdata", "0010_merge_0009_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParishProximityMatrix",
            fields=[
                ("proximity_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_parish_code", models.CharField(max_length=2)),
                ("candidate_parish_code", models.CharField(max_length=2)),
                ("proximity_rank", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "parish_proximity_matrix",
            },
        ),
        migrations.AddConstraint(
            model_name="parishproximitymatrix",
            constraint=models.UniqueConstraint(
                fields=("source_parish_code", "candidate_parish_code"),
                name="uq_parish_proximity_source_candidate",
            ),
        ),
        migrations.AddIndex(
            model_name="parishproximitymatrix",
            index=models.Index(
                fields=["source_parish_code", "proximity_rank"],
                name="md_parish_src_rank_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parishproximitymatrix",
            index=models.Index(
                fields=["candidate_parish_code"],
                name="md_parish_candidate_idx",
            ),
        ),
        migrations.RunPython(seed_parish_proximity_matrix, unseed_parish_proximity_matrix),
    ]
