from __future__ import annotations

from contextlib import ExitStack
from unittest.mock import patch

from django.db import connection
from django.test import TestCase
from django.utils import timezone

from masterdata.services import iam_data_access


class CreateUserWithPrimaryTenantTests(TestCase):
    tenant_id = 9901

    def setUp(self) -> None:
        self._ensure_tables()
        self._delete_test_users()
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO tenant (
                    tenant_id,
                    tenant_code,
                    tenant_name,
                    tenant_type,
                    status_code,
                    create_by_id,
                    update_by_id,
                    version_nbr
                )
                VALUES (%s, %s, %s, %s, 'A', 'SYSTEM', 'SYSTEM', 1)
                ON CONFLICT (tenant_id) DO UPDATE
                SET status_code = 'A',
                    tenant_code = EXCLUDED.tenant_code,
                    tenant_name = EXCLUDED.tenant_name,
                    tenant_type = EXCLUDED.tenant_type
                """,
                [self.tenant_id, "IAMTEST", "IAM TEST TENANT", "PARTNER"],
            )

    def tearDown(self) -> None:
        self._delete_test_users()

    def _ensure_tables(self) -> None:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS tenant (
                    tenant_id integer PRIMARY KEY,
                    tenant_code varchar(20) NOT NULL UNIQUE,
                    tenant_name varchar(120) NOT NULL,
                    tenant_type varchar(20) NOT NULL,
                    status_code char(1) DEFAULT 'A' NOT NULL,
                    create_by_id varchar(20) DEFAULT 'SYSTEM' NOT NULL,
                    create_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    update_by_id varchar(20) DEFAULT 'SYSTEM' NOT NULL,
                    update_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    version_nbr integer DEFAULT 1 NOT NULL
                )
                """
            )
            if connection.vendor == "sqlite":
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS "user" (
                        user_id integer PRIMARY KEY AUTOINCREMENT,
                        email varchar(200) NOT NULL UNIQUE,
                        password_hash varchar(256) NOT NULL,
                        first_name varchar(100),
                        last_name varchar(100),
                        full_name varchar(200),
                        is_active boolean DEFAULT TRUE NOT NULL,
                        assigned_warehouse_id integer,
                        create_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        update_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        username varchar(60) UNIQUE,
                        password_algo varchar(20) DEFAULT 'argon2id' NOT NULL,
                        mfa_enabled boolean DEFAULT FALSE NOT NULL,
                        failed_login_count smallint DEFAULT 0 NOT NULL,
                        agency_id integer,
                        status_code char(1) DEFAULT 'A' NOT NULL,
                        version_nbr integer DEFAULT 1 NOT NULL,
                        user_name varchar(20) NOT NULL,
                        login_count integer DEFAULT 0 NOT NULL,
                        phone varchar(50),
                        timezone varchar(50) DEFAULT 'America/Jamaica' NOT NULL,
                        language varchar(10) DEFAULT 'en' NOT NULL
                    )
                    """
                )
            else:
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS "user" (
                        user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email varchar(200) NOT NULL UNIQUE,
                        password_hash varchar(256) NOT NULL,
                        first_name varchar(100),
                        last_name varchar(100),
                        full_name varchar(200),
                        is_active boolean DEFAULT TRUE NOT NULL,
                        assigned_warehouse_id integer,
                        create_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        update_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        username varchar(60) UNIQUE,
                        password_algo varchar(20) DEFAULT 'argon2id' NOT NULL,
                        mfa_enabled boolean DEFAULT FALSE NOT NULL,
                        failed_login_count smallint DEFAULT 0 NOT NULL,
                        agency_id integer,
                        status_code char(1) DEFAULT 'A' NOT NULL,
                        version_nbr integer DEFAULT 1 NOT NULL,
                        user_name varchar(20) NOT NULL,
                        login_count integer DEFAULT 0 NOT NULL,
                        phone varchar(50),
                        timezone varchar(50) DEFAULT 'America/Jamaica' NOT NULL,
                        language varchar(10) DEFAULT 'en' NOT NULL
                    )
                    """
                )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS tenant_user (
                    tenant_id integer NOT NULL,
                    user_id integer NOT NULL,
                    is_primary_tenant boolean DEFAULT FALSE NOT NULL,
                    access_level varchar(20) DEFAULT 'STANDARD',
                    assigned_at timestamp DEFAULT CURRENT_TIMESTAMP,
                    assigned_by integer,
                    status_code char(1) DEFAULT 'A' NOT NULL,
                    create_by_id varchar(20) DEFAULT 'SYSTEM' NOT NULL,
                    create_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    PRIMARY KEY (tenant_id, user_id)
                )
                """
            )

    def _delete_test_users(self) -> None:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                DELETE FROM tenant_user
                WHERE user_id IN (
                    SELECT user_id
                    FROM "user"
                    WHERE email LIKE %s
                )
                """,
                ["iam-service-%@example.test"],
            )
            cursor.execute(
                """
                DELETE FROM "user"
                WHERE email LIKE %s
                """,
                ["iam-service-%@example.test"],
            )

    def _record_data(self, suffix: str) -> dict[str, object]:
        return {
            "username": f"iam_service_{suffix}",
            "email": f"iam-service-{suffix}@example.test",
            "first_name": "Service",
            "last_name": suffix.title(),
            "full_name": f"Service {suffix.title()}",
            "is_active": True,
            "status_code": "A",
        }

    def _sqlite_create_record(self, _table_key: str, data: dict[str, object], _actor_id: str):
        now = timezone.now()
        username = str(data.get("username") or data.get("email") or "KEYCLOAK_USER")
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO "user" (
                    email,
                    password_hash,
                    first_name,
                    last_name,
                    full_name,
                    is_active,
                    create_dtime,
                    update_dtime,
                    username,
                    password_algo,
                    mfa_enabled,
                    failed_login_count,
                    status_code,
                    version_nbr,
                    user_name,
                    login_count,
                    timezone,
                    language
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, 'argon2id', FALSE, 0, %s, 1, %s, 0, %s, %s)
                """,
                [
                    data["email"],
                    data.get("password_hash", ""),
                    data.get("first_name"),
                    data.get("last_name"),
                    data.get("full_name"),
                    data.get("is_active", True),
                    now,
                    now,
                    username,
                    data.get("status_code", "A"),
                    username[:20],
                    data.get("timezone", "America/Jamaica"),
                    data.get("language", "en"),
                ],
            )
            return int(cursor.lastrowid), []

    def _sqlite_assign_tenant_user(
        self,
        tenant_id: int,
        user_id: int,
        access_level: str,
        assigned_by: object,
        *,
        is_primary_tenant: bool = False,
    ) -> bool:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO tenant_user (
                    tenant_id,
                    user_id,
                    is_primary_tenant,
                    access_level,
                    assigned_by,
                    status_code,
                    create_by_id,
                    create_dtime
                )
                VALUES (%s, %s, %s, %s, %s, 'A', %s, CURRENT_TIMESTAMP)
                ON CONFLICT (tenant_id, user_id) DO UPDATE
                SET
                    is_primary_tenant = excluded.is_primary_tenant,
                    access_level = excluded.access_level,
                    assigned_by = excluded.assigned_by,
                    status_code = 'A'
                """,
                [
                    tenant_id,
                    user_id,
                    is_primary_tenant,
                    access_level,
                    int(assigned_by) if str(assigned_by).isdigit() else None,
                    str(assigned_by or "SYSTEM")[:20],
                ],
            )
        return True

    def _sqlite_service_patches(self):
        if connection.vendor != "sqlite":
            return ()
        return (
            patch("masterdata.services.data_access.create_record", side_effect=self._sqlite_create_record),
            patch("masterdata.services.iam_data_access.assign_tenant_user", side_effect=self._sqlite_assign_tenant_user),
        )

    def test_create_user_with_primary_tenant_happy_path(self):
        with ExitStack() as stack:
            for service_patch in self._sqlite_service_patches():
                stack.enter_context(service_patch)
            user_id, warnings = iam_data_access.create_user_with_primary_tenant(
                tenant_id=self.tenant_id,
                record_data=self._record_data("happy"),
                actor_id="99",
            )

        self.assertIsInstance(user_id, int)
        self.assertEqual(warnings, [])
        with connection.cursor() as cursor:
            cursor.execute('SELECT email FROM "user" WHERE user_id = %s', [user_id])
            self.assertEqual(cursor.fetchone()[0], "iam-service-happy@example.test")
            cursor.execute(
                """
                SELECT is_primary_tenant, access_level
                FROM tenant_user
                WHERE tenant_id = %s AND user_id = %s AND status_code = 'A'
                """,
                [self.tenant_id, user_id],
            )
            membership = cursor.fetchone()
        self.assertIsNotNone(membership)
        self.assertTrue(bool(membership[0]))
        self.assertEqual(membership[1], "STANDARD")

    def test_raises_user_create_record_error_when_create_returns_none(self):
        with patch(
            "masterdata.services.data_access.create_record",
            return_value=(None, ["db_unique_violation"]),
        ):
            with self.assertRaises(iam_data_access.UserCreateRecordError) as ctx:
                iam_data_access.create_user_with_primary_tenant(
                    tenant_id=self.tenant_id,
                    record_data=self._record_data("create_fail"),
                    actor_id="99",
                )
        self.assertEqual(ctx.exception.warnings, ["db_unique_violation"])

    def test_raises_membership_error_when_assign_returns_false(self):
        with (
            patch("masterdata.services.data_access.create_record", return_value=(123, [])),
            patch("masterdata.services.iam_data_access.assign_tenant_user", return_value=False),
        ):
            with self.assertRaises(iam_data_access.UserPrimaryTenantMembershipError):
                iam_data_access.create_user_with_primary_tenant(
                    tenant_id=self.tenant_id,
                    record_data=self._record_data("assign_false"),
                    actor_id="99",
                )

    def test_raises_membership_error_when_verification_fails(self):
        with (
            patch("masterdata.services.data_access.create_record", return_value=(123, [])),
            patch("masterdata.services.iam_data_access.assign_tenant_user", return_value=True),
            patch(
                "masterdata.services.iam_data_access.verify_user_primary_tenant_membership",
                side_effect=iam_data_access.UserPrimaryTenantMembershipError("bad membership"),
            ),
        ):
            with self.assertRaises(iam_data_access.UserPrimaryTenantMembershipError):
                iam_data_access.create_user_with_primary_tenant(
                    tenant_id=self.tenant_id,
                    record_data=self._record_data("verify_fail"),
                    actor_id="99",
                )

    def test_rolls_back_user_row_when_membership_fails(self):
        record_data = self._record_data("rollback")
        with ExitStack() as stack:
            if connection.vendor == "sqlite":
                stack.enter_context(
                    patch(
                        "masterdata.services.data_access.create_record",
                        side_effect=self._sqlite_create_record,
                    )
                )
            stack.enter_context(
                patch("masterdata.services.iam_data_access.assign_tenant_user", return_value=False)
            )
            with self.assertRaises(iam_data_access.UserPrimaryTenantMembershipError):
                iam_data_access.create_user_with_primary_tenant(
                    tenant_id=self.tenant_id,
                    record_data=record_data,
                    actor_id="99",
                )

        with connection.cursor() as cursor:
            cursor.execute('SELECT COUNT(*) FROM "user" WHERE email = %s', [record_data["email"]])
            self.assertEqual(cursor.fetchone()[0], 0)
