from __future__ import annotations

from unittest.mock import MagicMock, patch

from django.contrib.auth.hashers import check_password, make_password
from django.core.exceptions import ImproperlyConfigured
from django.core.management.base import CommandError
from django.db import IntegrityError, connection
from django.test import TestCase, override_settings
from django.utils import timezone

from accounts.managers import DmisUserManager
from accounts.management.commands.create_admin_user import Command as CreateAdminUserCommand
from accounts.models import DmisUser
from masterdata.services import iam_data_access


class DmisUserTestMixin:
    tenant_id = 9902

    def setUp(self) -> None:
        self._ensure_tables()
        self._delete_test_users()

    def tearDown(self) -> None:
        self._delete_test_users()

    def _ensure_tables(self) -> None:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS tenant (
                    tenant_id integer PRIMARY KEY,
                    tenant_code varchar(20) NOT NULL UNIQUE,
                    tenant_name varchar(120) NOT NULL,
                    tenant_type varchar(20) NOT NULL,
                    status_code char(1) DEFAULT 'A' NOT NULL,
                    create_by_id varchar(20) DEFAULT 'SYSTEM' NOT NULL,
                    create_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    update_by_id varchar(20) DEFAULT 'SYSTEM' NOT NULL,
                    update_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    version_nbr integer DEFAULT 1 NOT NULL
                )
                """
            )
            if connection.vendor == "sqlite":
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS "user" (
                        user_id integer PRIMARY KEY AUTOINCREMENT,
                        email varchar(200) NOT NULL UNIQUE,
                        password_hash varchar(256) NOT NULL,
                        first_name varchar(100),
                        last_name varchar(100),
                        full_name varchar(200),
                        is_active boolean DEFAULT TRUE NOT NULL,
                        organization varchar(200),
                        job_title varchar(200),
                        phone varchar(50),
                        timezone varchar(50) DEFAULT 'America/Jamaica' NOT NULL,
                        language varchar(10) DEFAULT 'en' NOT NULL,
                        notification_preferences text,
                        assigned_warehouse_id integer,
                        last_login_at timestamp,
                        create_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        update_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        username varchar(60) UNIQUE,
                        password_algo varchar(20) DEFAULT 'argon2id' NOT NULL,
                        mfa_enabled boolean DEFAULT FALSE NOT NULL,
                        mfa_secret varchar(64),
                        failed_login_count smallint DEFAULT 0 NOT NULL,
                        lock_until_at timestamp,
                        password_changed_at timestamp,
                        agency_id integer,
                        status_code char(1) DEFAULT 'A' NOT NULL,
                        version_nbr integer DEFAULT 1 NOT NULL,
                        user_name varchar(20) NOT NULL,
                        login_count integer DEFAULT 0 NOT NULL
                    )
                    """
                )
            else:
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS "user" (
                        user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email varchar(200) NOT NULL UNIQUE,
                        password_hash varchar(256) NOT NULL,
                        first_name varchar(100),
                        last_name varchar(100),
                        full_name varchar(200),
                        is_active boolean DEFAULT TRUE NOT NULL,
                        organization varchar(200),
                        job_title varchar(200),
                        phone varchar(50),
                        timezone varchar(50) DEFAULT 'America/Jamaica' NOT NULL,
                        language varchar(10) DEFAULT 'en' NOT NULL,
                        notification_preferences text,
                        assigned_warehouse_id integer,
                        last_login_at timestamp,
                        create_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        update_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        username varchar(60) UNIQUE,
                        password_algo varchar(20) DEFAULT 'argon2id' NOT NULL,
                        mfa_enabled boolean DEFAULT FALSE NOT NULL,
                        mfa_secret varchar(64),
                        failed_login_count smallint DEFAULT 0 NOT NULL,
                        lock_until_at timestamp,
                        password_changed_at timestamp,
                        agency_id integer,
                        status_code char(1) DEFAULT 'A' NOT NULL,
                        version_nbr integer DEFAULT 1 NOT NULL,
                        user_name varchar(20) NOT NULL,
                        login_count integer DEFAULT 0 NOT NULL
                    )
                    """
                )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS role (
                    id integer PRIMARY KEY,
                    code varchar(50) NOT NULL UNIQUE,
                    name varchar(100) NOT NULL
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS user_role (
                    user_id integer NOT NULL,
                    role_id integer NOT NULL,
                    assigned_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    assigned_by integer,
                    create_by_id varchar(20) DEFAULT 'system' NOT NULL,
                    create_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    update_by_id varchar(20) DEFAULT 'system' NOT NULL,
                    update_dtime timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    version_nbr integer DEFAULT 1 NOT NULL,
                    PRIMARY KEY (user_id, role_id)
                )
                """
            )

    def _delete_test_users(self) -> None:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                DELETE FROM user_role
                WHERE user_id IN (
                    SELECT user_id
                    FROM "user"
                    WHERE email LIKE %s
                )
                """,
                ["accounts-%@example.test"],
            )
            cursor.execute(
                """
                DELETE FROM "user"
                WHERE email LIKE %s
                """,
                ["accounts-%@example.test"],
            )

    def _insert_user(
        self,
        *,
        user_id: int,
        username: str,
        email: str,
        password_hash: str | None = None,
        full_name: str = "Accounts Fixture",
    ) -> None:
        now = timezone.now()
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO "user" (
                    user_id,
                    email,
                    password_hash,
                    first_name,
                    last_name,
                    full_name,
                    is_active,
                    organization,
                    job_title,
                    phone,
                    timezone,
                    language,
                    notification_preferences,
                    assigned_warehouse_id,
                    last_login_at,
                    create_dtime,
                    update_dtime,
                    username,
                    password_algo,
                    mfa_enabled,
                    mfa_secret,
                    failed_login_count,
                    lock_until_at,
                    password_changed_at,
                    agency_id,
                    status_code,
                    version_nbr,
                    user_name,
                    login_count
                )
                VALUES (
                    %s, %s, %s, 'Accounts', 'Fixture', %s, TRUE,
                    'ODPEM', 'Tester', '555-0100', 'America/Jamaica',
                    'en', '{}', 12, %s, %s, %s, %s, %s, FALSE,
                    NULL, 0, NULL, %s, 34, 'A', 3, 'ACCOUNTS_TST', 5
                )
                """,
                [
                    user_id,
                    email,
                    password_hash or make_password("phase1-pass"),
                    full_name,
                    now,
                    now,
                    now,
                    username,
                    "pbkdf2_sha256",
                    now,
                ],
            )


class DmisUserModelTests(DmisUserTestMixin, TestCase):
    def test_loads_existing_dmis_user_fields(self) -> None:
        self._insert_user(
            user_id=880001,
            username="accounts_fixture_tst",
            email="accounts-fixture@example.test",
        )

        user = DmisUser.objects.get(username="accounts_fixture_tst")

        self.assertEqual(user.user_id, 880001)
        self.assertEqual(user.email, "accounts-fixture@example.test")
        self.assertEqual(user.full_name, "Accounts Fixture")
        self.assertEqual(user.user_name, "ACCOUNTS_TST")
        self.assertEqual(user.organization, "ODPEM")
        self.assertEqual(user.assigned_warehouse_id, 12)
        self.assertEqual(user.agency_id, 34)
        self.assertEqual(user.status_code, "A")
        self.assertEqual(user.version_nbr, 3)
        self.assertEqual(user.login_count, 5)
        self.assertTrue(check_password("phase1-pass", user.password))


class DmisUserSecurityTests(DmisUserTestMixin, TestCase):
    def test_is_superuser_is_always_false(self) -> None:
        self._insert_user(
            user_id=880002,
            username="accounts_security_tst",
            email="accounts-security@example.test",
        )
        loaded_user = DmisUser.objects.get(username="accounts_security_tst")
        new_user = DmisUser(username="new_security_tst", email="accounts-new@example.test")

        self.assertIs(loaded_user.is_superuser, False)
        self.assertIs(new_user.is_superuser, False)
        loaded_user.__dict__["is_superuser"] = True
        self.assertIs(loaded_user.is_superuser, False)
        with self.assertRaises(AttributeError):
            loaded_user.is_superuser = True

    def test_has_perm_does_not_short_circuit(self) -> None:
        self._insert_user(
            user_id=880003,
            username="accounts_perm_tst",
            email="accounts-perm@example.test",
        )
        user = DmisUser.objects.get(username="accounts_perm_tst")

        self.assertIs(user.is_superuser, False)
        self.assertFalse(user.has_perm("accounts.anything"))


@override_settings(
    AUTH_ENABLED=False,
    DEV_AUTH_ENABLED=True,
    TEST_DEV_AUTH_ENABLED=True,
)
class DmisUserManagerTests(DmisUserTestMixin, TestCase):
    def test_create_user_calls_tenant_first_helper(self) -> None:
        self._insert_user(
            user_id=880004,
            username="accounts_create_tst",
            email="accounts-create@example.test",
            password_hash="",
            full_name="Create Placeholder",
        )

        with patch(
            "accounts.managers.create_user_with_primary_tenant",
            return_value=(880004, []),
        ) as helper:
            user = DmisUser.objects.create_user(
                "accounts_create_tst",
                "accounts-create@example.test",
                "user-pass",
                tenant_id=self.tenant_id,
                user_name="ACCOUNTS_CREATE",
            )

        helper.assert_called_once()
        kwargs = helper.call_args.kwargs
        self.assertEqual(kwargs["tenant_id"], self.tenant_id)
        self.assertEqual(kwargs["actor_id"], "system")
        self.assertEqual(kwargs["record_data"]["username"], "accounts_create_tst")
        self.assertEqual(kwargs["record_data"]["user_name"], "ACCOUNTS_CREATE")
        self.assertEqual(kwargs["record_data"]["email"], "accounts-create@example.test")
        self.assertTrue(check_password("user-pass", kwargs["record_data"]["password_hash"]))
        self.assertEqual(user.user_id, 880004)
        self.assertTrue(user.check_password("user-pass"))

    def test_create_user_requires_tenant(self) -> None:
        with self.assertRaises(ImproperlyConfigured):
            DmisUser.objects.create_user(
                "accounts_missing_tenant_tst",
                "accounts-missing-tenant@example.test",
                "user-pass",
            )

    def test_create_user_translates_helper_exceptions(self) -> None:
        with patch(
            "accounts.managers.create_user_with_primary_tenant",
            side_effect=iam_data_access.UserPrimaryTenantMembershipError("bad membership"),
        ):
            with self.assertRaises(IntegrityError):
                DmisUser.objects.create_user(
                    "accounts_integrity_tst",
                    "accounts-integrity@example.test",
                    "user-pass",
                    tenant_id=self.tenant_id,
                )

    def test_create_superuser_assigns_system_administrator_role(self) -> None:
        returned_user = DmisUser(
            user_id=880005,
            username="accounts_admin_tst",
            email="accounts-admin@example.test",
            is_active=True,
        )
        cursor = MagicMock()
        cursor.fetchone.return_value = (7,)
        cursor_context = MagicMock()
        cursor_context.__enter__.return_value = cursor
        cursor_context.__exit__.return_value = False

        with (
            patch.object(DmisUserManager, "create_user", return_value=returned_user),
            patch("accounts.managers.connection.cursor", return_value=cursor_context),
        ):
            user = DmisUser.objects.create_superuser(
                "accounts_admin_tst",
                "accounts-admin@example.test",
                "admin-pass",
                tenant_id=self.tenant_id,
            )

        self.assertEqual(user.user_id, 880005)
        executed_sql = "\n".join(str(call.args[0]) for call in cursor.execute.call_args_list)
        self.assertIn("SELECT id", executed_sql)
        self.assertIn("INSERT INTO user_role", executed_sql)
        insert_call = next(
            call for call in cursor.execute.call_args_list if "INSERT INTO user_role" in str(call.args[0])
        )
        insert_params = insert_call.args[1]
        self.assertEqual(insert_params[0], 880005)
        self.assertEqual(insert_params[1], 7)


@override_settings(
    AUTH_ENABLED=False,
    DEV_AUTH_ENABLED=True,
    TEST_DEV_AUTH_ENABLED=True,
)
class CreateAdminUserCommandTests(TestCase):
    def test_handle_rejects_dual_tenant_selectors(self) -> None:
        with self.assertRaisesMessage(CommandError, "Exactly one tenant selector"):
            CreateAdminUserCommand().handle(
                username="accounts_admin_cmd_tst",
                email="accounts-admin-cmd@example.test",
                password="admin-pass",
                tenant_id=9902,
                tenant_code="ODPEM",
            )

    def test_handle_rejects_invalid_tenant_selectors_before_password_prompt(self) -> None:
        invalid_selectors = (
            {"tenant_id": 9902, "tenant_code": "ODPEM"},
            {"tenant_id": None, "tenant_code": ""},
        )
        with patch("accounts.management.commands.create_admin_user.getpass.getpass") as prompt:
            for selectors in invalid_selectors:
                with self.subTest(selectors=selectors):
                    with self.assertRaisesMessage(
                        CommandError,
                        "Exactly one tenant selector",
                    ):
                        CreateAdminUserCommand().handle(
                            username="accounts_admin_cmd_tst",
                            email="accounts-admin-cmd@example.test",
                            **selectors,
                        )
            prompt.assert_not_called()
