-- Migration 007: Drop and recreate transfer table with updated schema
-- Changes: 
-- 1. Rename event_id to eligible_event_id
-- 2. Change foreign key references from inventory to warehouse
-- 3. Add 'P' status to status_code check constraint
-- 4. Rename constraints to DRIMS naming standards
-- 5. Add proper default for transfer_date

BEGIN;

-- Step 1: Drop dependent tables (if they exist)
-- Note: These will be recreated by the application models
DROP TABLE IF EXISTS xfintake CASCADE;
DROP TABLE IF EXISTS transfer_item CASCADE;

-- Step 2: Drop transfer table
DROP TABLE IF EXISTS transfer CASCADE;

-- Step 3: Create transfer table with correct schema
CREATE TABLE transfer
(
    transfer_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_transfer PRIMARY KEY,

    -- Inventories involved in transfer (reference warehouse, not inventory)
    fr_inventory_id INTEGER NOT NULL
        CONSTRAINT fk_transfer_warehouse1 REFERENCES warehouse(warehouse_id),
    to_inventory_id INTEGER NOT NULL
        CONSTRAINT fk_transfer_warehouse2 REFERENCES warehouse(warehouse_id),
    
    -- Optional eligible event for which the transfer is being done
    eligible_event_id INTEGER
        CONSTRAINT fk_transfer_event REFERENCES event(event_id),

    transfer_date DATE NOT NULL DEFAULT CURRENT_DATE
        CONSTRAINT c_transfer_1 CHECK (transfer_date <= CURRENT_DATE),

    -- Reason for transfer
    reason_text VARCHAR(255),

    status_code CHAR(1) NOT NULL
        -- Status of transfer transaction: D=Draft, C=Completed, V=Verified, P=Processed
        CONSTRAINT c_transfer_2 CHECK (status_code IN ('D','C','V','P')),

    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE,
    verify_by_id VARCHAR(20) NOT NULL,
    verify_dtime TIMESTAMP(0) WITHOUT TIME ZONE,
    version_nbr INTEGER NOT NULL
);

-- Step 4: Create indexes to retrieve transfer by date, source and destination
CREATE INDEX dk_transfer_1 ON transfer(transfer_date);
CREATE INDEX dk_transfer_2 ON transfer(fr_inventory_id);
CREATE INDEX dk_transfer_3 ON transfer(to_inventory_id);

-- Step 5: Verify table was created
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM pg_tables 
        WHERE tablename = 'transfer' 
        AND schemaname = 'public'
    ) THEN
        RAISE EXCEPTION 'Failed to create transfer table';
    END IF;
END $$;

COMMIT;

-- Notes:
-- 1. transfer_item and xfintake tables will be recreated by SQLAlchemy models
-- 2. All data in transfer-related tables has been cleared (0 rows existed)
-- 3. Foreign keys now correctly reference warehouse(warehouse_id) instead of inventory
-- 4. Status codes: D=Draft, C=Completed, V=Verified, P=Processed
