-- Wave 1: Reference catalogs for governed master values
-- Baseline: live schema `dmis`

BEGIN;

CREATE TABLE IF NOT EXISTS public.ref_tenant_type (
    tenant_type_code character varying(30) PRIMARY KEY,
    tenant_type_name character varying(120) NOT NULL,
    description text,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT ref_tenant_type_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar]))
);

CREATE TABLE IF NOT EXISTS public.ref_event_phase (
    phase_code character varying(20) PRIMARY KEY,
    phase_name character varying(80) NOT NULL,
    sort_order integer NOT NULL,
    description text,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT ref_event_phase_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar]))
);

CREATE TABLE IF NOT EXISTS public.ref_procurement_method (
    method_code character varying(40) PRIMARY KEY,
    method_name character varying(120) NOT NULL,
    description text,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT ref_procurement_method_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar]))
);

CREATE TABLE IF NOT EXISTS public.ref_approval_tier (
    tier_code character varying(20) PRIMARY KEY,
    tier_name character varying(120) NOT NULL,
    description text,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT ref_approval_tier_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar]))
);

CREATE TABLE IF NOT EXISTS public.reason_code_master (
    reason_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_domain character varying(40) NOT NULL,
    reason_code character varying(40) NOT NULL,
    reason_desc character varying(255) NOT NULL,
    requires_comment_flag boolean DEFAULT false NOT NULL,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT reason_code_master_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT reason_code_master_uq UNIQUE (reason_domain, reason_code)
);

INSERT INTO public.ref_tenant_type (tenant_type_code, tenant_type_name, description)
VALUES
    ('NATIONAL', 'National Authority', 'National disaster management authority'),
    ('MILITARY', 'Military', 'Military or security partner'),
    ('SOCIAL_SERVICES', 'Social Services', 'Social services and welfare organizations'),
    ('PARISH', 'Parish/Municipal', 'Parish-level governing body'),
    ('NGO', 'NGO', 'Non-governmental organization'),
    ('MINISTRY', 'Ministry', 'Government ministry'),
    ('EXTERNAL', 'External Partner', 'External or humanitarian partner'),
    ('INFRASTRUCTURE', 'Infrastructure Utility', 'Lifeline / utility partner'),
    ('PUBLIC', 'Public View', 'Public transparency tenant')
ON CONFLICT (tenant_type_code) DO NOTHING;

INSERT INTO public.ref_event_phase (phase_code, phase_name, sort_order, description)
VALUES
    ('SURGE', 'Surge', 10, 'Acute response window'),
    ('STABILIZED', 'Stabilized', 20, 'Post-surge stabilization'),
    ('RECOVERY', 'Recovery', 30, 'Recovery transition period'),
    ('BASELINE', 'Baseline', 40, 'Steady-state readiness')
ON CONFLICT (phase_code) DO NOTHING;

INSERT INTO public.ref_procurement_method (method_code, method_name, description)
VALUES
    ('EMERGENCY_DIRECT_PURCHASE', 'Emergency Direct Purchase', 'Emergency direct purchase method'),
    ('FRAMEWORK_CALLOFF', 'Framework Agreement Call-Off', 'Framework contract call-off'),
    ('COMPETITIVE_QUOTATION', 'Competitive Quotation', 'Competitive quotation process'),
    ('OPEN_TENDER', 'Open Tender', 'Open tender process')
ON CONFLICT (method_code) DO NOTHING;

INSERT INTO public.ref_approval_tier (tier_code, tier_name, description)
VALUES
    ('TIER_1', 'Tier 1', 'Lowest approval threshold'),
    ('TIER_2', 'Tier 2', 'Intermediate approval threshold'),
    ('TIER_3', 'Tier 3', 'High approval threshold'),
    ('EMERGENCY', 'Emergency Tier', 'Emergency escalation threshold')
ON CONFLICT (tier_code) DO NOTHING;

INSERT INTO public.reason_code_master (reason_domain, reason_code, reason_desc, requires_comment_flag)
VALUES
    ('ALLOCATION_OVERRIDE', 'PRIORITY_EXCEPTION', 'Allocation deviated due to field priority exception', true),
    ('ALLOCATION_OVERRIDE', 'SUPPLY_SHORTFALL', 'Allocation reduced due to supply shortfall', true),
    ('WORKFLOW_REJECTION', 'INSUFFICIENT_JUSTIFICATION', 'Submission missing required business justification', true),
    ('WORKFLOW_REJECTION', 'POLICY_NONCOMPLIANCE', 'Submission violates configured policy', true),
    ('DISPOSAL', 'EXPIRED_STOCK', 'Stock expired and approved for disposal', true),
    ('DISPOSAL', 'DAMAGED_STOCK', 'Stock damaged/unfit and approved for disposal', true),
    ('SOD_EXCEPTION', 'EMERGENCY_OVERRIDE', 'Temporary emergency override for segregation of duties', true)
ON CONFLICT (reason_domain, reason_code) DO NOTHING;

COMMIT;

