-- Wave 2: Governance and policy master tables

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '15min';

CREATE TABLE IF NOT EXISTS public.approval_threshold_policy (
    policy_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type character varying(30) NOT NULL,
    procurement_method_code character varying(40),
    min_amount numeric(15,2) NOT NULL,
    max_amount numeric(15,2),
    currency_code character varying(10) DEFAULT 'JMD'::character varying NOT NULL,
    approval_tier_code character varying(20) NOT NULL,
    requires_ppc boolean DEFAULT false NOT NULL,
    requires_cabinet boolean DEFAULT false NOT NULL,
    tenant_id integer,
    effective_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT approval_threshold_policy_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT approval_threshold_policy_amount_check CHECK ((min_amount >= 0.00) AND (max_amount IS NULL OR max_amount >= min_amount)),
    CONSTRAINT approval_threshold_policy_entity_check CHECK (entity_type = ANY (ARRAY['PROCUREMENT', 'DISBURSEMENT', 'TRANSFER', 'RELIEF_REQUEST']))
);

CREATE TABLE IF NOT EXISTS public.approval_authority_matrix (
    matrix_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    threshold_policy_id integer NOT NULL,
    role_code character varying(50) NOT NULL,
    approval_sequence integer NOT NULL,
    is_mandatory boolean DEFAULT true NOT NULL,
    same_parish_only boolean DEFAULT false NOT NULL,
    cross_parish_only boolean DEFAULT false NOT NULL,
    tenant_id integer,
    effective_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT approval_authority_matrix_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT approval_authority_matrix_sequence_check CHECK (approval_sequence > 0),
    CONSTRAINT approval_authority_matrix_uq UNIQUE (threshold_policy_id, approval_sequence, role_code)
);

CREATE TABLE IF NOT EXISTS public.workflow_transition_rule (
    rule_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type character varying(30) NOT NULL,
    from_status character varying(30) NOT NULL,
    to_status character varying(30) NOT NULL,
    role_code character varying(50) NOT NULL,
    requires_reason_code boolean DEFAULT false NOT NULL,
    reason_domain character varying(40),
    enforce_sod boolean DEFAULT false NOT NULL,
    tenant_id integer,
    effective_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT workflow_transition_rule_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT workflow_transition_rule_reason_domain_check CHECK ((NOT requires_reason_code) OR (reason_domain IS NOT NULL)),
    CONSTRAINT workflow_transition_rule_uq UNIQUE (entity_type, from_status, to_status, role_code, tenant_id)
);

CREATE TABLE IF NOT EXISTS public.allocation_rule (
    rule_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name character varying(120) NOT NULL,
    event_phase_code character varying(20) NOT NULL,
    item_criticality character varying(10),
    agency_priority integer,
    geographic_scope character varying(20) DEFAULT 'NATIONAL'::character varying NOT NULL,
    population_weight numeric(5,2) DEFAULT 0.00 NOT NULL,
    urgency_weight numeric(5,2) DEFAULT 0.00 NOT NULL,
    criticality_weight numeric(5,2) DEFAULT 0.00 NOT NULL,
    chronology_weight numeric(5,2) DEFAULT 0.00 NOT NULL,
    is_override_allowed boolean DEFAULT true NOT NULL,
    tenant_id integer,
    effective_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT allocation_rule_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT allocation_rule_scope_check CHECK (geographic_scope = ANY (ARRAY['NATIONAL', 'PARISH', 'COMMUNITY'])),
    CONSTRAINT allocation_rule_phase_check CHECK (event_phase_code = ANY (ARRAY['SURGE', 'STABILIZED', 'RECOVERY', 'BASELINE']))
);

CREATE TABLE IF NOT EXISTS public.allocation_limit (
    limit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL,
    agency_id integer NOT NULL,
    item_category_id integer,
    max_qty numeric(15,2),
    max_value numeric(15,2),
    currency_code character varying(10) DEFAULT 'JMD'::character varying NOT NULL,
    tenant_id integer,
    effective_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT allocation_limit_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT allocation_limit_at_least_one_limit CHECK (max_qty IS NOT NULL OR max_value IS NOT NULL),
    CONSTRAINT allocation_limit_nonnegative_check CHECK (
        (max_qty IS NULL OR max_qty >= 0.00) AND
        (max_value IS NULL OR max_value >= 0.00)
    )
);

CREATE TABLE IF NOT EXISTS public.user_tenant_role (
    tenant_id integer NOT NULL,
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    assigned_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    assigned_by integer,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT user_tenant_role_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT user_tenant_role_pkey PRIMARY KEY (tenant_id, user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.item_category_baseline_rate (
    baseline_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id integer NOT NULL,
    event_phase_code character varying(20) NOT NULL,
    baseline_rate_per_hour numeric(10,4) NOT NULL,
    tenant_id integer,
    effective_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT item_category_baseline_rate_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT item_category_baseline_rate_positive CHECK (baseline_rate_per_hour >= 0.0000),
    CONSTRAINT item_category_baseline_rate_phase_check CHECK (event_phase_code = ANY (ARRAY['SURGE', 'STABILIZED', 'RECOVERY', 'BASELINE'])),
    CONSTRAINT item_category_baseline_rate_uq UNIQUE (category_id, event_phase_code, tenant_id, effective_date)
);

CREATE TABLE IF NOT EXISTS public.mpf_criteria_weight (
    weight_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criteria_code character varying(30) NOT NULL,
    criteria_desc character varying(255) NOT NULL,
    loe_objective character varying(30) NOT NULL,
    event_phase_code character varying(20),
    weight_value numeric(6,3) NOT NULL,
    tenant_id integer,
    effective_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    status_code character(1) DEFAULT 'A'::bpchar NOT NULL,
    create_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    create_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_by_id character varying(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    update_dtime timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version_nbr integer DEFAULT 1 NOT NULL,
    CONSTRAINT mpf_criteria_weight_status_check CHECK (status_code = ANY (ARRAY['A'::bpchar, 'I'::bpchar])),
    CONSTRAINT mpf_criteria_weight_range_check CHECK (weight_value >= 0.000 AND weight_value <= 1.000)
);

CREATE OR REPLACE FUNCTION public.prevent_overlap_approval_threshold_policy()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status_code = 'A' THEN
        IF EXISTS (
            SELECT 1
            FROM public.approval_threshold_policy p
            WHERE p.policy_id <> COALESCE(NEW.policy_id, -1)
              AND p.status_code = 'A'
              AND p.entity_type = NEW.entity_type
              AND COALESCE(p.procurement_method_code, '') = COALESCE(NEW.procurement_method_code, '')
              AND p.currency_code = NEW.currency_code
              AND COALESCE(p.tenant_id, -1) = COALESCE(NEW.tenant_id, -1)
              AND numrange(p.min_amount, COALESCE(p.max_amount, 1e18::numeric), '[]')
                  && numrange(NEW.min_amount, COALESCE(NEW.max_amount, 1e18::numeric), '[]')
              AND daterange(p.effective_date, COALESCE(p.expiry_date, '9999-12-31'::date), '[]')
                  && daterange(NEW.effective_date, COALESCE(NEW.expiry_date, '9999-12-31'::date), '[]')
        ) THEN
            RAISE EXCEPTION 'Overlapping active approval threshold policy detected for entity %, method %, tenant %',
                NEW.entity_type, COALESCE(NEW.procurement_method_code, 'ALL'), COALESCE(NEW.tenant_id::text, 'GLOBAL');
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_prevent_overlap_approval_threshold_policy'
          AND tgrelid = 'public.approval_threshold_policy'::regclass
    ) THEN
        CREATE TRIGGER trg_prevent_overlap_approval_threshold_policy
            BEFORE INSERT OR UPDATE
            ON public.approval_threshold_policy
            FOR EACH ROW
            EXECUTE FUNCTION public.prevent_overlap_approval_threshold_policy();
    END IF;
END $$;

-- Prevent duplicate global rules where tenant_id is NULL
CREATE UNIQUE INDEX IF NOT EXISTS workflow_transition_rule_uq_global
    ON public.workflow_transition_rule (entity_type, from_status, to_status, role_code)
    WHERE tenant_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS item_category_baseline_rate_uq_global
    ON public.item_category_baseline_rate (category_id, event_phase_code, effective_date)
    WHERE tenant_id IS NULL;

-- Foreign keys
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_threshold_policy_tenant_fkey') THEN
        ALTER TABLE public.approval_threshold_policy
            ADD CONSTRAINT approval_threshold_policy_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(tenant_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_threshold_policy_tier_fkey') THEN
        ALTER TABLE public.approval_threshold_policy
            ADD CONSTRAINT approval_threshold_policy_tier_fkey FOREIGN KEY (approval_tier_code) REFERENCES public.ref_approval_tier(tier_code);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_threshold_policy_method_fkey') THEN
        ALTER TABLE public.approval_threshold_policy
            ADD CONSTRAINT approval_threshold_policy_method_fkey FOREIGN KEY (procurement_method_code) REFERENCES public.ref_procurement_method(method_code);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_threshold_policy_currency_fkey') THEN
        ALTER TABLE public.approval_threshold_policy
            ADD CONSTRAINT approval_threshold_policy_currency_fkey FOREIGN KEY (currency_code) REFERENCES public.currency(currency_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_authority_matrix_policy_fkey') THEN
        ALTER TABLE public.approval_authority_matrix
            ADD CONSTRAINT approval_authority_matrix_policy_fkey FOREIGN KEY (threshold_policy_id) REFERENCES public.approval_threshold_policy(policy_id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_authority_matrix_role_fkey') THEN
        ALTER TABLE public.approval_authority_matrix
            ADD CONSTRAINT approval_authority_matrix_role_fkey FOREIGN KEY (role_code) REFERENCES public.role(code);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_authority_matrix_tenant_fkey') THEN
        ALTER TABLE public.approval_authority_matrix
            ADD CONSTRAINT approval_authority_matrix_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(tenant_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'workflow_transition_rule_role_fkey') THEN
        ALTER TABLE public.workflow_transition_rule
            ADD CONSTRAINT workflow_transition_rule_role_fkey FOREIGN KEY (role_code) REFERENCES public.role(code);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'workflow_transition_rule_tenant_fkey') THEN
        ALTER TABLE public.workflow_transition_rule
            ADD CONSTRAINT workflow_transition_rule_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(tenant_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'allocation_rule_tenant_fkey') THEN
        ALTER TABLE public.allocation_rule
            ADD CONSTRAINT allocation_rule_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(tenant_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'allocation_rule_phase_fkey') THEN
        ALTER TABLE public.allocation_rule
            ADD CONSTRAINT allocation_rule_phase_fkey FOREIGN KEY (event_phase_code) REFERENCES public.ref_event_phase(phase_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'allocation_limit_event_fkey') THEN
        ALTER TABLE public.allocation_limit
            ADD CONSTRAINT allocation_limit_event_fkey FOREIGN KEY (event_id) REFERENCES public.event(event_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'allocation_limit_agency_fkey') THEN
        ALTER TABLE public.allocation_limit
            ADD CONSTRAINT allocation_limit_agency_fkey FOREIGN KEY (agency_id) REFERENCES public.agency(agency_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'allocation_limit_category_fkey') THEN
        ALTER TABLE public.allocation_limit
            ADD CONSTRAINT allocation_limit_category_fkey FOREIGN KEY (item_category_id) REFERENCES public.itemcatg(category_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'allocation_limit_currency_fkey') THEN
        ALTER TABLE public.allocation_limit
            ADD CONSTRAINT allocation_limit_currency_fkey FOREIGN KEY (currency_code) REFERENCES public.currency(currency_code);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'allocation_limit_tenant_fkey') THEN
        ALTER TABLE public.allocation_limit
            ADD CONSTRAINT allocation_limit_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(tenant_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_tenant_role_tenant_fkey') THEN
        ALTER TABLE public.user_tenant_role
            ADD CONSTRAINT user_tenant_role_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(tenant_id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_tenant_role_user_fkey') THEN
        ALTER TABLE public.user_tenant_role
            ADD CONSTRAINT user_tenant_role_user_fkey FOREIGN KEY (user_id) REFERENCES public."user"(user_id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_tenant_role_role_fkey') THEN
        ALTER TABLE public.user_tenant_role
            ADD CONSTRAINT user_tenant_role_role_fkey FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_tenant_role_assigned_by_fkey') THEN
        ALTER TABLE public.user_tenant_role
            ADD CONSTRAINT user_tenant_role_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public."user"(user_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'item_category_baseline_rate_category_fkey') THEN
        ALTER TABLE public.item_category_baseline_rate
            ADD CONSTRAINT item_category_baseline_rate_category_fkey FOREIGN KEY (category_id) REFERENCES public.itemcatg(category_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'item_category_baseline_rate_phase_fkey') THEN
        ALTER TABLE public.item_category_baseline_rate
            ADD CONSTRAINT item_category_baseline_rate_phase_fkey FOREIGN KEY (event_phase_code) REFERENCES public.ref_event_phase(phase_code);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'item_category_baseline_rate_tenant_fkey') THEN
        ALTER TABLE public.item_category_baseline_rate
            ADD CONSTRAINT item_category_baseline_rate_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(tenant_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'mpf_criteria_weight_phase_fkey') THEN
        ALTER TABLE public.mpf_criteria_weight
            ADD CONSTRAINT mpf_criteria_weight_phase_fkey FOREIGN KEY (event_phase_code) REFERENCES public.ref_event_phase(phase_code);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'mpf_criteria_weight_tenant_fkey') THEN
        ALTER TABLE public.mpf_criteria_weight
            ADD CONSTRAINT mpf_criteria_weight_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(tenant_id);
    END IF;
END $$;

COMMIT;
