-- ============================================================================
-- DRIMS - Add donation_doc Table for Document Attachments
-- ============================================================================
-- Purpose: Add donation_doc table to support attaching documents 
--          (receipts, manifests, delivery notices) to donations
--
-- Target State:
--   - New table: donation_doc with document_id as identity PK
--   - FK: donation_doc.donation_id → donation.donation_id
--   - Supported file types: application/pdf, image/jpeg
--   - Optimistic locking via version_nbr
--
-- Prerequisites: donation table must exist with donation_id as PK
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Pre-Migration Validation
-- ============================================================================

-- Verify donation table exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'donation'
    ) THEN
        RAISE EXCEPTION 'Migration aborted: donation table does not exist';
    END IF;
    
    -- Verify donation_id column exists as primary key
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu 
            ON tc.constraint_name = kcu.constraint_name
        WHERE tc.table_name = 'donation'
            AND tc.constraint_type = 'PRIMARY KEY'
            AND kcu.column_name = 'donation_id'
    ) THEN
        RAISE EXCEPTION 'Migration aborted: donation_id is not the primary key of donation table';
    END IF;
    
    RAISE NOTICE '✓ Pre-migration validation passed';
END $$;

-- ============================================================================
-- SECTION 2: Create donation_doc Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS donation_doc
(
    -- Unique ID assigned to document - Tracks document throughout system
    document_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_donation_doc PRIMARY KEY,

    donation_id INTEGER NOT NULL
        CONSTRAINT fk_donation_doc_donation REFERENCES donation(donation_id),

    -- Type of document e.g. Receipt, Manifest, Bill of materials, Delivery notice, etc.
    document_type VARCHAR(40) NOT NULL,

    -- Description of document purpose and/or content
    document_desc VARCHAR(255) NOT NULL,

    -- Original name of the uploaded file
    file_name VARCHAR(80) NOT NULL,

    -- Format of file. Supported formats: application/pdf, image/jpeg
    file_type VARCHAR(30) NOT NULL
        CONSTRAINT c_donation_doc_1
        CHECK (file_type IN ('application/pdf','image/jpeg')),

    -- Size of file in MB e.g. 5MB
    file_size VARCHAR(20),

    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);

-- Add table comment
COMMENT ON TABLE donation_doc IS 'Document attachments for donations (receipts, manifests, delivery notices)';

-- Add column comments
COMMENT ON COLUMN donation_doc.document_id IS 'Primary key - auto-generated document identifier';
COMMENT ON COLUMN donation_doc.donation_id IS 'Foreign key to donation table';
COMMENT ON COLUMN donation_doc.document_type IS 'Type of document (Receipt, Manifest, Bill of materials, Delivery notice, etc.)';
COMMENT ON COLUMN donation_doc.document_desc IS 'Description of document purpose and content';
COMMENT ON COLUMN donation_doc.file_name IS 'Original name of the uploaded file';
COMMENT ON COLUMN donation_doc.file_type IS 'MIME type of file (application/pdf or image/jpeg)';
COMMENT ON COLUMN donation_doc.file_size IS 'Size of file in MB';
COMMENT ON COLUMN donation_doc.version_nbr IS 'Optimistic locking version number';

-- ============================================================================
-- SECTION 3: Create Indexes
-- ============================================================================

-- Create index on donation_id for faster lookups of documents by donation
CREATE INDEX idx_donation_doc_donation_id ON donation_doc(donation_id);

-- Create index on document_type for filtering by type
CREATE INDEX idx_donation_doc_type ON donation_doc(document_type);

-- ============================================================================
-- SECTION 4: Verification
-- ============================================================================

-- Verify the new structure
DO $$
DECLARE
    v_pk_name TEXT;
    v_fk_name TEXT;
    v_check_count INTEGER;
    v_idx_donation_count INTEGER;
    v_idx_type_count INTEGER;
BEGIN
    -- Check primary key constraint
    SELECT conname INTO v_pk_name
    FROM pg_constraint
    WHERE conrelid = 'donation_doc'::regclass 
      AND contype = 'p';
    
    IF v_pk_name != 'pk_donation_doc' THEN
        RAISE EXCEPTION 'Primary key constraint not found or incorrectly named: %', v_pk_name;
    END IF;
    
    -- Check foreign key constraint
    SELECT conname INTO v_fk_name
    FROM pg_constraint
    WHERE conrelid = 'donation_doc'::regclass 
      AND contype = 'f'
      AND conname = 'fk_donation_doc_donation';
    
    IF v_fk_name IS NULL THEN
        RAISE EXCEPTION 'Foreign key constraint fk_donation_doc_donation not found';
    END IF;
    
    -- Check CHECK constraint for file_type
    SELECT COUNT(*) INTO v_check_count
    FROM pg_constraint
    WHERE conrelid = 'donation_doc'::regclass 
      AND contype = 'c'
      AND conname = 'c_donation_doc_1';
    
    IF v_check_count != 1 THEN
        RAISE EXCEPTION 'Check constraint c_donation_doc_1 not found';
    END IF;
    
    -- Check index on donation_id
    SELECT COUNT(*) INTO v_idx_donation_count
    FROM pg_indexes
    WHERE tablename = 'donation_doc' 
      AND indexname = 'idx_donation_doc_donation_id';
    
    IF v_idx_donation_count != 1 THEN
        RAISE EXCEPTION 'Index idx_donation_doc_donation_id not found';
    END IF;
    
    -- Check index on document_type
    SELECT COUNT(*) INTO v_idx_type_count
    FROM pg_indexes
    WHERE tablename = 'donation_doc' 
      AND indexname = 'idx_donation_doc_type';
    
    IF v_idx_type_count != 1 THEN
        RAISE EXCEPTION 'Index idx_donation_doc_type not found';
    END IF;
    
    RAISE NOTICE '✓ All constraints and indexes verified successfully';
    RAISE NOTICE '  - Primary key: pk_donation_doc on document_id';
    RAISE NOTICE '  - Foreign key: fk_donation_doc_donation (donation_doc.donation_id → donation.donation_id)';
    RAISE NOTICE '  - Check constraint: c_donation_doc_1 (file_type validation)';
    RAISE NOTICE '  - Index: idx_donation_doc_donation_id on donation_id';
    RAISE NOTICE '  - Index: idx_donation_doc_type on document_type';
END $$;

COMMIT;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Summary:
-- ✓ donation_doc table created with document_id as identity PK
-- ✓ Foreign key to donation table established
-- ✓ CHECK constraint enforces valid file types (PDF, JPEG)
-- ✓ All audit fields present (create_by_id, create_dtime, update_by_id, update_dtime, version_nbr)
-- ✓ Indexes created on donation_id and document_type for performance
-- ✓ All constraint names follow existing naming conventions
-- ✓ No changes to existing tables, columns, or constraints
-- ============================================================================
