from __future__ import annotations

from collections.abc import Iterable

REQUEST_STATUS_DRAFT = "DRAFT"
REQUEST_STATUS_SUBMITTED = "SUBMITTED"
REQUEST_STATUS_UNDER_ELIGIBILITY_REVIEW = "UNDER_ELIGIBILITY_REVIEW"
REQUEST_STATUS_APPROVED_FOR_FULFILLMENT = "APPROVED_FOR_FULFILLMENT"
REQUEST_STATUS_PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED"
REQUEST_STATUS_FULFILLED = "FULFILLED"
REQUEST_STATUS_INELIGIBLE = "INELIGIBLE"
REQUEST_STATUS_REJECTED = "REJECTED"
REQUEST_STATUS_CANCELLED = "CANCELLED"

PACKAGE_STATUS_DRAFT = "DRAFT"
PACKAGE_STATUS_PENDING_OVERRIDE_APPROVAL = "PENDING_OVERRIDE_APPROVAL"
PACKAGE_STATUS_COMMITTED = "COMMITTED"
PACKAGE_STATUS_CONSOLIDATING = "CONSOLIDATING"
PACKAGE_STATUS_READY_FOR_DISPATCH = "READY_FOR_DISPATCH"
PACKAGE_STATUS_READY_FOR_PICKUP = "READY_FOR_PICKUP"
PACKAGE_STATUS_REJECTED = "REJECTED"
PACKAGE_STATUS_DISPATCHED = "DISPATCHED"
PACKAGE_STATUS_RECEIVED = "RECEIVED"
PACKAGE_STATUS_SPLIT = "SPLIT"
PACKAGE_STATUS_CANCELLED = "CANCELLED"

OVERRIDE_STATUS_PENDING_APPROVAL = "PENDING_APPROVAL"
OVERRIDE_STATUS_APPROVED = "APPROVED"
OVERRIDE_STATUS_RETURNED_FOR_ADJUSTMENT = "RETURNED_FOR_ADJUSTMENT"
OVERRIDE_STATUS_REJECTED = "REJECTED"

DISPATCH_STATUS_READY = "READY"
DISPATCH_STATUS_IN_TRANSIT = "IN_TRANSIT"
DISPATCH_STATUS_DELIVERED = "DELIVERED"
DISPATCH_STATUS_RECEIVED = "RECEIVED"
DISPATCH_STATUS_CANCELLED = "CANCELLED"

FULFILLMENT_MODE_DIRECT = "DIRECT"
FULFILLMENT_MODE_PICKUP_AT_STAGING = "PICKUP_AT_STAGING"
FULFILLMENT_MODE_DELIVER_FROM_STAGING = "DELIVER_FROM_STAGING"
FULFILLMENT_MODES = (
    FULFILLMENT_MODE_DIRECT,
    FULFILLMENT_MODE_PICKUP_AT_STAGING,
    FULFILLMENT_MODE_DELIVER_FROM_STAGING,
)

STAGING_SELECTION_BASIS_SAME_PARISH = "SAME_PARISH"
STAGING_SELECTION_BASIS_PROXIMITY_MATRIX = "PROXIMITY_MATRIX"
STAGING_SELECTION_BASIS_ALPHABETICAL_FALLBACK = "ALPHABETICAL_FALLBACK"
STAGING_SELECTION_BASIS_MANUAL_OVERRIDE = "MANUAL_OVERRIDE"

CONSOLIDATION_STATUS_AWAITING_LEGS = "AWAITING_LEGS"
CONSOLIDATION_STATUS_LEGS_IN_TRANSIT = "LEGS_IN_TRANSIT"
CONSOLIDATION_STATUS_PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
CONSOLIDATION_STATUS_ALL_RECEIVED = "ALL_RECEIVED"
CONSOLIDATION_STATUS_PARTIAL_RELEASE_REQUESTED = "PARTIAL_RELEASE_REQUESTED"

CONSOLIDATION_LEG_STATUS_PLANNED = "PLANNED"
CONSOLIDATION_LEG_STATUS_IN_TRANSIT = "IN_TRANSIT"
CONSOLIDATION_LEG_STATUS_RECEIVED_AT_STAGING = "RECEIVED_AT_STAGING"
CONSOLIDATION_LEG_STATUS_CANCELLED = "CANCELLED"

ORIGIN_MODE_SELF = "SELF"
ORIGIN_MODE_FOR_SUBORDINATE = "FOR_SUBORDINATE"
ORIGIN_MODE_ODPEM_BRIDGE = "ODPEM_BRIDGE"

QUEUE_CODE_ELIGIBILITY = "ELIGIBILITY_REVIEW"
QUEUE_CODE_FULFILLMENT = "PACKAGE_FULFILLMENT"
QUEUE_CODE_OVERRIDE = "OVERRIDE_APPROVAL"
QUEUE_CODE_DISPATCH = "DISPATCH"
QUEUE_CODE_RECEIPT = "RECEIPT_CONFIRMATION"
QUEUE_CODE_CONSOLIDATION_DISPATCH = "CONSOLIDATION_DISPATCH"
QUEUE_CODE_STAGING_RECEIPT = "STAGING_RECEIPT"
QUEUE_CODE_PICKUP_RELEASE = "PICKUP_RELEASE"
QUEUE_CODE_PARTIAL_RELEASE_APPROVAL = "PARTIAL_RELEASE_APPROVAL"
QUEUE_CODE_REQUESTER = "REQUEST_TRACKING"

EVENT_REQUEST_SUBMITTED = "REQUEST_SUBMITTED"
EVENT_REQUEST_APPROVED = "REQUEST_APPROVED"
EVENT_REQUEST_REJECTED = "REQUEST_REJECTED"
EVENT_REQUEST_INELIGIBLE = "REQUEST_INELIGIBLE"
EVENT_PACKAGE_LOCKED = "PACKAGE_LOCKED"
EVENT_PACKAGE_UNLOCKED = "PACKAGE_UNLOCKED"
EVENT_OVERRIDE_REQUESTED = "PACKAGE_OVERRIDE_REQUESTED"
EVENT_OVERRIDE_APPROVED = "PACKAGE_OVERRIDE_APPROVED"
EVENT_OVERRIDE_RETURNED_FOR_ADJUSTMENT = "PACKAGE_OVERRIDE_RETURNED_FOR_ADJUSTMENT"
EVENT_OVERRIDE_REJECTED = "PACKAGE_OVERRIDE_REJECTED"
EVENT_PACKAGE_COMMITTED = "PACKAGE_COMMITTED"
EVENT_PACKAGE_CANCELLED = "PACKAGE_CANCELLED"
EVENT_PACKAGE_SPLIT = "PACKAGE_SPLIT"
EVENT_CONSOLIDATION_PLANNED = "CONSOLIDATION_PLANNED"
EVENT_CONSOLIDATION_DISPATCHED = "CONSOLIDATION_DISPATCHED"
EVENT_STAGING_RECEIPT_RECORDED = "STAGING_RECEIPT_RECORDED"
EVENT_STAGED_DELIVERY_READY = "STAGED_DELIVERY_READY"
EVENT_PICKUP_RELEASED = "PICKUP_RELEASED"
EVENT_PARTIAL_RELEASE_REQUESTED = "PARTIAL_RELEASE_REQUESTED"
EVENT_PARTIAL_RELEASE_APPROVED = "PARTIAL_RELEASE_APPROVED"
EVENT_DISPATCH_COMPLETED = "DISPATCH_COMPLETED"
EVENT_RECEIPT_CONFIRMED = "RECEIPT_CONFIRMED"

ACTION_OVERRIDE_APPROVED = "OVERRIDE_APPROVED"
ACTION_OVERRIDE_RETURNED_FOR_ADJUSTMENT = "OVERRIDE_RETURNED_FOR_ADJUSTMENT"
ACTION_OVERRIDE_REJECTED = "OVERRIDE_REJECTED"
ACTION_CONSOLIDATION_LEG_DISPATCHED = "CONSOLIDATION_LEG_DISPATCHED"
ACTION_CONSOLIDATION_LEG_RECEIVED = "CONSOLIDATION_LEG_RECEIVED"
ACTION_PICKUP_RELEASE_COMPLETED = "PICKUP_RELEASE_COMPLETED"
ACTION_PARTIAL_RELEASE_REQUESTED = "PARTIAL_RELEASE_REQUESTED"
ACTION_PARTIAL_RELEASE_APPROVED = "PARTIAL_RELEASE_APPROVED"

PARTIAL_RELEASE_STATUS_PENDING = "PENDING"
PARTIAL_RELEASE_STATUS_APPROVED = "APPROVED"

ROLE_DEPUTY_DG = "DEPUTY_DG"
ROLE_DIRECTOR_OF_PEOD = "DIRECTOR_OF_PEOD"
ROLE_DG = "DG"
ROLE_LOGISTICS_OFFICER = "LOGISTICS_OFFICER"
ROLE_LOGISTICS_MANAGER = "LOGISTICS_MANAGER"
ROLE_INVENTORY_CLERK = "INVENTORY_CLERK"
ROLE_SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR"

ELIGIBILITY_ROLE_CODES = (
    ROLE_DEPUTY_DG,
    ROLE_DIRECTOR_OF_PEOD,
    ROLE_DG,
)
FULFILLMENT_ROLE_CODES = (
    ROLE_LOGISTICS_OFFICER,
    ROLE_LOGISTICS_MANAGER,
)
DISPATCH_ROLE_CODES = (
    ROLE_INVENTORY_CLERK,
    ROLE_LOGISTICS_OFFICER,
    ROLE_LOGISTICS_MANAGER,
)

ROLE_ALIAS_MAP = {
    "ODPEM_DDG": ROLE_DEPUTY_DG,
    "DEPUTY_DG": ROLE_DEPUTY_DG,
    "DDG": ROLE_DEPUTY_DG,
    "ODPEM_DIR_PEOD": ROLE_DIRECTOR_OF_PEOD,
    "DIR_PEOD": ROLE_DIRECTOR_OF_PEOD,
    "DIRECTOR_OF_PEOD": ROLE_DIRECTOR_OF_PEOD,
    "TST_DIR_PEOD": ROLE_DIRECTOR_OF_PEOD,
    "ODPEM_DG": ROLE_DG,
    "DIRECTOR_GENERAL": ROLE_DG,
    "TST_DG": ROLE_DG,
    "DG": ROLE_DG,
    "LOGISTICS_OFFICER": ROLE_LOGISTICS_OFFICER,
    "TST_LOGISTICS_OFFICER": ROLE_LOGISTICS_OFFICER,
    "LOGISTICS_MANAGER": ROLE_LOGISTICS_MANAGER,
    "TST_LOGISTICS_MANAGER": ROLE_LOGISTICS_MANAGER,
    "ODPEM_LOGISTICS_MANAGER": ROLE_LOGISTICS_MANAGER,
    "INVENTORY_CLERK": ROLE_INVENTORY_CLERK,
}

STATUS_LABELS = {
    REQUEST_STATUS_DRAFT: "Draft",
    REQUEST_STATUS_SUBMITTED: "Submitted",
    REQUEST_STATUS_UNDER_ELIGIBILITY_REVIEW: "Under Eligibility Review",
    REQUEST_STATUS_APPROVED_FOR_FULFILLMENT: "Approved For Fulfillment",
    REQUEST_STATUS_PARTIALLY_FULFILLED: "Partially Fulfilled",
    REQUEST_STATUS_FULFILLED: "Fulfilled",
    REQUEST_STATUS_INELIGIBLE: "Ineligible",
    REQUEST_STATUS_REJECTED: "Rejected",
    REQUEST_STATUS_CANCELLED: "Cancelled",
    PACKAGE_STATUS_DRAFT: "Draft",
    PACKAGE_STATUS_PENDING_OVERRIDE_APPROVAL: "Pending Override Approval",
    PACKAGE_STATUS_COMMITTED: "Committed",
    PACKAGE_STATUS_CONSOLIDATING: "Consolidating",
    PACKAGE_STATUS_READY_FOR_DISPATCH: "Ready For Dispatch",
    PACKAGE_STATUS_READY_FOR_PICKUP: "Ready For Pickup",
    PACKAGE_STATUS_REJECTED: "Rejected",
    PACKAGE_STATUS_DISPATCHED: "Dispatched",
    PACKAGE_STATUS_RECEIVED: "Received",
    PACKAGE_STATUS_SPLIT: "Split",
    PACKAGE_STATUS_CANCELLED: "Cancelled",
    DISPATCH_STATUS_READY: "Ready",
    DISPATCH_STATUS_IN_TRANSIT: "In Transit",
    DISPATCH_STATUS_DELIVERED: "Delivered",
    DISPATCH_STATUS_RECEIVED: "Received",
    DISPATCH_STATUS_CANCELLED: "Cancelled",
    CONSOLIDATION_STATUS_AWAITING_LEGS: "Awaiting Legs",
    CONSOLIDATION_STATUS_LEGS_IN_TRANSIT: "Legs In Transit",
    CONSOLIDATION_STATUS_PARTIALLY_RECEIVED: "Partially Received",
    CONSOLIDATION_STATUS_ALL_RECEIVED: "All Received",
    CONSOLIDATION_STATUS_PARTIAL_RELEASE_REQUESTED: "Partial Release Requested",
    CONSOLIDATION_LEG_STATUS_PLANNED: "Planned",
    CONSOLIDATION_LEG_STATUS_IN_TRANSIT: "In Transit",
    CONSOLIDATION_LEG_STATUS_RECEIVED_AT_STAGING: "Received At Staging",
    CONSOLIDATION_LEG_STATUS_CANCELLED: "Cancelled",
}


def normalize_role_codes(role_codes: Iterable[str] | None) -> tuple[str, ...]:
    normalized: list[str] = []
    for raw_code in role_codes or ():
        code = str(raw_code or "").strip().upper()
        if not code:
            continue
        canonical = ROLE_ALIAS_MAP.get(code, code)
        if canonical not in normalized:
            normalized.append(canonical)
    return tuple(normalized)
