from __future__ import annotations

from collections.abc import Iterable

REQUEST_STATUS_DRAFT = "DRAFT"
REQUEST_STATUS_SUBMITTED = "SUBMITTED"
REQUEST_STATUS_UNDER_ELIGIBILITY_REVIEW = "UNDER_ELIGIBILITY_REVIEW"
REQUEST_STATUS_APPROVED_FOR_FULFILLMENT = "APPROVED_FOR_FULFILLMENT"
REQUEST_STATUS_PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED"
REQUEST_STATUS_FULFILLED = "FULFILLED"
REQUEST_STATUS_INELIGIBLE = "INELIGIBLE"
REQUEST_STATUS_REJECTED = "REJECTED"
REQUEST_STATUS_CANCELLED = "CANCELLED"

PACKAGE_STATUS_DRAFT = "DRAFT"
PACKAGE_STATUS_PENDING_OVERRIDE_APPROVAL = "PENDING_OVERRIDE_APPROVAL"
PACKAGE_STATUS_COMMITTED = "COMMITTED"
PACKAGE_STATUS_READY_FOR_DISPATCH = "READY_FOR_DISPATCH"
PACKAGE_STATUS_DISPATCHED = "DISPATCHED"
PACKAGE_STATUS_RECEIVED = "RECEIVED"
PACKAGE_STATUS_CANCELLED = "CANCELLED"

DISPATCH_STATUS_READY = "READY"
DISPATCH_STATUS_IN_TRANSIT = "IN_TRANSIT"
DISPATCH_STATUS_DELIVERED = "DELIVERED"
DISPATCH_STATUS_RECEIVED = "RECEIVED"
DISPATCH_STATUS_CANCELLED = "CANCELLED"

ORIGIN_MODE_SELF = "SELF"
ORIGIN_MODE_FOR_SUBORDINATE = "FOR_SUBORDINATE"
ORIGIN_MODE_ODPEM_BRIDGE = "ODPEM_BRIDGE"

QUEUE_CODE_ELIGIBILITY = "ELIGIBILITY_REVIEW"
QUEUE_CODE_FULFILLMENT = "PACKAGE_FULFILLMENT"
QUEUE_CODE_OVERRIDE = "OVERRIDE_APPROVAL"
QUEUE_CODE_DISPATCH = "DISPATCH"
QUEUE_CODE_RECEIPT = "RECEIPT_CONFIRMATION"
QUEUE_CODE_REQUESTER = "REQUEST_TRACKING"

EVENT_REQUEST_SUBMITTED = "REQUEST_SUBMITTED"
EVENT_REQUEST_APPROVED = "REQUEST_APPROVED"
EVENT_REQUEST_REJECTED = "REQUEST_REJECTED"
EVENT_REQUEST_INELIGIBLE = "REQUEST_INELIGIBLE"
EVENT_PACKAGE_LOCKED = "PACKAGE_LOCKED"
EVENT_OVERRIDE_REQUESTED = "PACKAGE_OVERRIDE_REQUESTED"
EVENT_OVERRIDE_APPROVED = "PACKAGE_OVERRIDE_APPROVED"
EVENT_PACKAGE_COMMITTED = "PACKAGE_COMMITTED"
EVENT_DISPATCH_COMPLETED = "DISPATCH_COMPLETED"
EVENT_RECEIPT_CONFIRMED = "RECEIPT_CONFIRMED"

ROLE_DEPUTY_DG = "DEPUTY_DG"
ROLE_DIRECTOR_OF_PEOD = "DIRECTOR_OF_PEOD"
ROLE_DG = "DG"
ROLE_LOGISTICS_OFFICER = "LOGISTICS_OFFICER"
ROLE_LOGISTICS_MANAGER = "LOGISTICS_MANAGER"
ROLE_INVENTORY_CLERK = "INVENTORY_CLERK"
ROLE_SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR"

ELIGIBILITY_ROLE_CODES = (
    ROLE_DEPUTY_DG,
    ROLE_DIRECTOR_OF_PEOD,
    ROLE_DG,
)
FULFILLMENT_ROLE_CODES = (
    ROLE_LOGISTICS_OFFICER,
    ROLE_LOGISTICS_MANAGER,
)
DISPATCH_ROLE_CODES = (
    ROLE_INVENTORY_CLERK,
    ROLE_LOGISTICS_OFFICER,
    ROLE_LOGISTICS_MANAGER,
)

ROLE_ALIAS_MAP = {
    "ODPEM_DDG": ROLE_DEPUTY_DG,
    "DEPUTY_DG": ROLE_DEPUTY_DG,
    "DDG": ROLE_DEPUTY_DG,
    "ODPEM_DIR_PEOD": ROLE_DIRECTOR_OF_PEOD,
    "DIR_PEOD": ROLE_DIRECTOR_OF_PEOD,
    "DIRECTOR_OF_PEOD": ROLE_DIRECTOR_OF_PEOD,
    "TST_DIR_PEOD": ROLE_DIRECTOR_OF_PEOD,
    "ODPEM_DG": ROLE_DG,
    "DIRECTOR_GENERAL": ROLE_DG,
    "TST_DG": ROLE_DG,
    "DG": ROLE_DG,
    "LOGISTICS_OFFICER": ROLE_LOGISTICS_OFFICER,
    "TST_LOGISTICS_OFFICER": ROLE_LOGISTICS_OFFICER,
    "LOGISTICS_MANAGER": ROLE_LOGISTICS_MANAGER,
    "TST_LOGISTICS_MANAGER": ROLE_LOGISTICS_MANAGER,
    "ODPEM_LOGISTICS_MANAGER": ROLE_LOGISTICS_MANAGER,
    "INVENTORY_CLERK": ROLE_INVENTORY_CLERK,
}

STATUS_LABELS = {
    REQUEST_STATUS_DRAFT: "Draft",
    REQUEST_STATUS_SUBMITTED: "Submitted",
    REQUEST_STATUS_UNDER_ELIGIBILITY_REVIEW: "Under Eligibility Review",
    REQUEST_STATUS_APPROVED_FOR_FULFILLMENT: "Approved For Fulfillment",
    REQUEST_STATUS_PARTIALLY_FULFILLED: "Partially Fulfilled",
    REQUEST_STATUS_FULFILLED: "Fulfilled",
    REQUEST_STATUS_INELIGIBLE: "Ineligible",
    REQUEST_STATUS_REJECTED: "Rejected",
    REQUEST_STATUS_CANCELLED: "Cancelled",
    PACKAGE_STATUS_DRAFT: "Draft",
    PACKAGE_STATUS_PENDING_OVERRIDE_APPROVAL: "Pending Override Approval",
    PACKAGE_STATUS_COMMITTED: "Committed",
    PACKAGE_STATUS_READY_FOR_DISPATCH: "Ready For Dispatch",
    PACKAGE_STATUS_DISPATCHED: "Dispatched",
    PACKAGE_STATUS_RECEIVED: "Received",
    PACKAGE_STATUS_CANCELLED: "Cancelled",
    DISPATCH_STATUS_READY: "Ready",
    DISPATCH_STATUS_IN_TRANSIT: "In Transit",
    DISPATCH_STATUS_DELIVERED: "Delivered",
    DISPATCH_STATUS_RECEIVED: "Received",
    DISPATCH_STATUS_CANCELLED: "Cancelled",
}


def normalize_role_codes(role_codes: Iterable[str] | None) -> tuple[str, ...]:
    normalized: list[str] = []
    for raw_code in role_codes or ():
        code = str(raw_code or "").strip().upper()
        if not code:
            continue
        canonical = ROLE_ALIAS_MAP.get(code, code)
        if canonical not in normalized:
            normalized.append(canonical)
    return tuple(normalized)
