from django.urls import path

from operations.views import (
    operations_dispatch_detail,
    operations_dispatch_handoff,
    operations_dispatch_queue,
    operations_dispatch_waybill,
    operations_consolidation_leg_dispatch,
    operations_consolidation_leg_receive,
    operations_consolidation_leg_waybill,
    operations_consolidation_legs,
    operations_eligibility_detail,
    operations_eligibility_decision,
    operations_eligibility_queue,
    operations_item_allocation_options,
    operations_item_allocation_preview,
    operations_package_staging_recommendation,
    operations_package_allocation_options,
    operations_package_commit_allocation,
    operations_package_current,
    operations_package_abandon_draft,
    operations_package_cancel,
    operations_package_draft,
    operations_package_unlock,
    operations_package_override_approve,
    operations_package_override_return,
    operations_package_override_reject,
    operations_packages_queue,
    operations_partial_release_approve,
    operations_partial_release_request,
    operations_pickup_release,
    operations_receipt_confirm,
    operations_request_detail,
    operations_request_reference_data,
    operations_request_submit,
    operations_requests,
    operations_tasks,
)

urlpatterns = [
    path("requests", operations_requests, name="operations_requests"),
    path("requests/reference-data", operations_request_reference_data, name="operations_request_reference_data"),
    path("requests/<int:reliefrqst_id>", operations_request_detail, name="operations_request_detail"),
    path("requests/<int:reliefrqst_id>/submit", operations_request_submit, name="operations_request_submit"),
    path("eligibility/queue", operations_eligibility_queue, name="operations_eligibility_queue"),
    path("eligibility/<int:reliefrqst_id>", operations_eligibility_detail, name="operations_eligibility_detail"),
    path(
        "eligibility/<int:reliefrqst_id>/decision",
        operations_eligibility_decision,
        name="operations_eligibility_decision",
    ),
    path("packages/queue", operations_packages_queue, name="operations_packages_queue"),
    path("packages/<int:reliefrqst_id>", operations_package_current, name="operations_package_current"),
    path(
        "packages/<int:reliefrqst_id>/staging-recommendation",
        operations_package_staging_recommendation,
        name="operations_package_staging_recommendation",
    ),
    path("packages/<int:reliefrqst_id>/draft", operations_package_draft, name="operations_package_draft"),
    path("packages/<int:reliefrqst_id>/unlock", operations_package_unlock, name="operations_package_unlock"),
    path(
        "packages/<int:reliefrqst_id>/allocation-options",
        operations_package_allocation_options,
        name="operations_package_allocation_options",
    ),
    path(
        "packages/<int:reliefrqst_id>/allocation-options/<int:item_id>",
        operations_item_allocation_options,
        name="operations_item_allocation_options",
    ),
    path(
        "packages/<int:reliefrqst_id>/allocation-options/<int:item_id>/preview",
        operations_item_allocation_preview,
        name="operations_item_allocation_preview",
    ),
    path(
        "packages/<int:reliefrqst_id>/allocations/commit",
        operations_package_commit_allocation,
        name="operations_package_commit_allocation",
    ),
    path(
        "packages/<int:reliefrqst_id>/allocations/override-approve",
        operations_package_override_approve,
        name="operations_package_override_approve",
    ),
    path(
        "packages/<int:reliefrqst_id>/allocations/override-return",
        operations_package_override_return,
        name="operations_package_override_return",
    ),
    path(
        "packages/<int:reliefrqst_id>/allocations/override-reject",
        operations_package_override_reject,
        name="operations_package_override_reject",
    ),
    path(
        "packages/<int:reliefpkg_id>/consolidation-legs",
        operations_consolidation_legs,
        name="operations_consolidation_legs",
    ),
    path(
        "packages/<int:reliefpkg_id>/consolidation-legs/<int:leg_id>/dispatch",
        operations_consolidation_leg_dispatch,
        name="operations_consolidation_leg_dispatch",
    ),
    path(
        "packages/<int:reliefpkg_id>/consolidation-legs/<int:leg_id>/receive",
        operations_consolidation_leg_receive,
        name="operations_consolidation_leg_receive",
    ),
    path(
        "packages/<int:reliefpkg_id>/consolidation-legs/<int:leg_id>/waybill",
        operations_consolidation_leg_waybill,
        name="operations_consolidation_leg_waybill",
    ),
    path(
        "packages/<int:reliefpkg_id>/partial-release/request",
        operations_partial_release_request,
        name="operations_partial_release_request",
    ),
    path(
        "packages/<int:reliefpkg_id>/partial-release/approve",
        operations_partial_release_approve,
        name="operations_partial_release_approve",
    ),
    path(
        "packages/<int:reliefpkg_id>/pickup-release",
        operations_pickup_release,
        name="operations_pickup_release",
    ),
    path(
        "packages/<int:reliefpkg_id>/cancel",
        operations_package_cancel,
        name="operations_package_cancel",
    ),
    path(
        "packages/<int:reliefpkg_id>/abandon-draft",
        operations_package_abandon_draft,
        name="operations_package_abandon_draft",
    ),
    path("dispatch/queue", operations_dispatch_queue, name="operations_dispatch_queue"),
    path("dispatch/<int:reliefpkg_id>", operations_dispatch_detail, name="operations_dispatch_detail"),
    path(
        "dispatch/<int:reliefpkg_id>/handoff",
        operations_dispatch_handoff,
        name="operations_dispatch_handoff",
    ),
    path(
        "dispatch/<int:reliefpkg_id>/waybill",
        operations_dispatch_waybill,
        name="operations_dispatch_waybill",
    ),
    path(
        "receipt-confirmation/<int:reliefpkg_id>",
        operations_receipt_confirm,
        name="operations_receipt_confirm",
    ),
    path("tasks", operations_tasks, name="operations_tasks"),
]

