"""
URL Safety Utilities for DMIS

Provides secure URL validation to prevent Open Redirect vulnerabilities.
All redirect targets from user input or database content should be validated
using these utilities before redirecting.
"""

from urllib.parse import urlparse, urljoin
from flask import request, url_for


def is_safe_url(target):
    """
    Validate that a redirect target stays within the same host.
    
    This prevents Open Redirect attacks where an attacker crafts a URL like:
    - /login?next=https://evil.com
    - /login?next=//evil.com
    - /login?next=javascript:alert(1)
    
    Args:
        target: The URL to validate (can be relative or absolute)
        
    Returns:
        bool: True if the URL is safe to redirect to, False otherwise
        
    Examples:
        >>> is_safe_url('/dashboard')  # Safe - relative URL
        True
        >>> is_safe_url('https://evil.com')  # Unsafe - external domain
        False
        >>> is_safe_url('//evil.com')  # Unsafe - protocol-relative URL
        False
    """
    if not target:
        return False

    normalized_target = target.strip()
    if not normalized_target:
        return False
    
    # Block protocol-relative URLs that could redirect to external sites
    if normalized_target.startswith('//'):
        return False
    
    # Block javascript: and data: URLs
    lower_target = normalized_target.lower()
    if lower_target.startswith(('javascript:', 'data:', 'vbscript:')):
        return False

    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, normalized_target))
    
    return (
        test_url.scheme in ('http', 'https')
        and ref_url.netloc == test_url.netloc
    )


def get_safe_redirect_url(target, default_endpoint='dashboard.index'):
    """
    Get a safe redirect URL, falling back to a default if the target is unsafe.
    
    This is the recommended way to handle user-provided redirect targets.
    It validates the target and returns a safe URL or a default.
    
    Args:
        target: The user-provided redirect target (can be None)
        default_endpoint: Flask endpoint to use as fallback (default: 'dashboard.index')
        
    Returns:
        str: A safe URL to redirect to
        
    Examples:
        >>> get_safe_redirect_url('/inventory')
        '/inventory'
        >>> get_safe_redirect_url('https://evil.com')
        '/dashboard/'  # Falls back to default
        >>> get_safe_redirect_url(None)
        '/dashboard/'  # Falls back to default
    """
    if target and is_safe_url(target):
        return target
    return url_for(default_endpoint)


def validate_internal_url(url):
    """
    Validate that a URL stored in the database is an internal URL.
    
    This is used for URLs that are generated by the application (like notification links)
    but should still be validated before redirecting for defense-in-depth.
    
    Args:
        url: The URL to validate
        
    Returns:
        bool: True if the URL is internal, False otherwise
    """
    if not url:
        return False
    
    # Internal URLs should start with / but not //
    if url.startswith('/') and not url.startswith('//'):
        # Additional check: shouldn't contain protocol markers
        lower_url = url.lower()
        if not any(marker in lower_url for marker in ['javascript:', 'data:', 'vbscript:']):
            return True
    
    # If it's an absolute URL, validate it's on the same host
    return is_safe_url(url)
