import { MasterTableConfig } from '../master-data.models';

export const AGENCY_CONFIG: MasterTableConfig = {
  tableKey: 'agencies',
  displayName: 'Agencies',
  icon: 'corporate_fare',
  pkField: 'agency_id',
  routePath: 'agencies',
  formMode: 'page',
  searchPlaceholder: 'Search by name or contact...',
  columns: [
    { field: 'agency_name', header: 'Name', type: 'text', sortable: true },
    { field: 'agency_type', header: 'Type', type: 'text', sortable: true },
    { field: 'parish_code', header: 'Parish', type: 'text', sortable: true, hideMobile: true },
    { field: 'contact_name', header: 'Contact', type: 'text', sortable: true, hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    { field: 'agency_name', label: 'Agency Name', type: 'text', required: true, maxLength: 120, uppercase: true,
      hint: 'Name shown when assigning requests, stock movements, or shelter support to this agency.',
      placeholder: 'Kingston Municipal Corporation',
      group: 'Basic Information' },
    { field: 'agency_type', label: 'Type', type: 'select', required: true,
      hint: 'Classifies whether the agency receives shelter or distribution work.',
      options: [
        { value: 'SHELTER', label: 'Shelter' },
        { value: 'DISTRIBUTOR', label: 'Distributor' },
      ],
      group: 'Basic Information' },
    { field: 'warehouse_id', label: 'Warehouse', type: 'lookup', lookupTable: 'warehouses',
      hint: 'Warehouse this agency works from for stock collection and day-to-day distribution.',
      group: 'Basic Information' },
    { field: 'agency_priority', label: 'Priority', type: 'number',
      hint: 'Order used when teams triage agency support during a response.',
      group: 'Basic Information' },
    { field: 'ineligible_event_id', label: 'Ineligible Event', type: 'lookup', lookupTable: 'events',
      hint: 'Event that currently blocks this agency from response assignments, when applicable.',
      group: 'Basic Information' },

    { field: 'address1_text', label: 'Address Line 1', type: 'text', required: true, maxLength: 255,
      hint: 'Primary address field teams use to reach this agency.',
      placeholder: '12 Camp Road, Kingston',
      group: 'Address' },
    { field: 'address2_text', label: 'Address Line 2', type: 'text', maxLength: 255,
      hint: 'Additional address detail such as building, floor, gate, or landmark.',
      placeholder: 'Gate 2, Logistics Office',
      group: 'Address' },
    { field: 'parish_code', label: 'Parish', type: 'lookup', required: true, lookupTable: 'parishes',
      hint: 'Parish used for routing, reporting, and field coordination.',
      group: 'Address' },

    { field: 'contact_name', label: 'Contact Name', type: 'text', required: true, maxLength: 50, uppercase: true,
      hint: 'Person field teams should contact about this agency.',
      placeholder: 'Kemar Brown',
      group: 'Contact' },
    { field: 'phone_no', label: 'Phone', type: 'phone', required: true, maxLength: 20,
      hint: 'Number field teams can call during operations.',
      placeholder: '+1 876 555 0123',
      pattern: '^\\+1 \\(\\d{3}\\) \\d{3}-\\d{4}$', patternMessage: 'Format: +1 (XXX) XXX-XXXX',
      group: 'Contact' },
    { field: 'email_text', label: 'Email', type: 'email', maxLength: 100,
      hint: 'Operational email used for confirmations and follow-up.',
      placeholder: 'ops@kingston.gov.jm',
      group: 'Contact' },

    { field: 'status_code', label: 'Status', type: 'select', required: true, defaultValue: 'A',
      hint: 'Active agencies can be selected for response work; inactive agencies remain for history.',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      group: 'Status' },
  ],
};
