import { MasterTableConfig } from '../master-data.models';

export const DONOR_CONFIG: MasterTableConfig = {
  tableKey: 'donors',
  displayName: 'Donors',
  icon: 'handshake',
  pkField: 'donor_id',
  routePath: 'donors',
  formMode: 'page',
  hasStatus: false,
  searchPlaceholder: 'Search by code or name...',
  columns: [
    { field: 'donor_code', header: 'Code', type: 'text', sortable: true },
    { field: 'donor_name', header: 'Name', type: 'text', sortable: true },
    { field: 'org_type_desc', header: 'Org Type', type: 'text', sortable: true, hideMobile: true },
    { field: 'phone_no', header: 'Phone', type: 'text', hideMobile: true },
  ],
  formFields: [
    { field: 'donor_code', label: 'Donor Code', type: 'text', required: true, maxLength: 16, uppercase: true,
      hint: 'Short donor key used to match donations, acknowledgements, and reports.',
      placeholder: '(set on creation; locked once saved)',
      readonlyOnEdit: true, group: 'Basic Information' },
    { field: 'donor_name', label: 'Donor Name', type: 'text', required: true, maxLength: 255, uppercase: true,
      hint: 'Official donor name shown on receipts, stock provenance, and reports.',
      placeholder: 'World Food Programme',
      group: 'Basic Information' },
    { field: 'org_type_desc', label: 'Organization Type', type: 'text', maxLength: 30,
      hint: 'Type of donor organization used for reporting and partner review.',
      placeholder: 'UN Agency',
      group: 'Basic Information' },

    { field: 'address1_text', label: 'Address Line 1', type: 'text', required: true, maxLength: 255,
      hint: 'Primary address used for donor correspondence and audit records.',
      placeholder: '14 Harbour Street, Kingston',
      group: 'Address' },
    { field: 'address2_text', label: 'Address Line 2', type: 'text', maxLength: 255,
      hint: 'Additional address detail such as building, floor, or mail stop.',
      placeholder: 'Suite 3B',
      group: 'Address' },
    { field: 'country_id', label: 'Country', type: 'lookup', required: true, lookupTable: 'countries', defaultValue: 388,
      hint: 'Country this donor is based in for reporting and partner context.',
      group: 'Address' },

    { field: 'phone_no', label: 'Phone', type: 'phone', required: true, maxLength: 20,
      hint: 'Number teams can call to confirm donation details.',
      placeholder: '+1 876 555 0123',
      pattern: '^\\+1 \\(\\d{3}\\) \\d{3}-\\d{4}$', patternMessage: 'Format: +1 (XXX) XXX-XXXX',
      group: 'Contact' },
    { field: 'email_text', label: 'Email', type: 'email', maxLength: 100,
      hint: 'Email used for donation confirmations and follow-up.',
      placeholder: 'donations@example.org',
      group: 'Contact' },
  ],
};
