import { MasterTableConfig } from '../master-data.models';

export const EVENT_CONFIG: MasterTableConfig = {
  tableKey: 'events',
  displayName: 'Events',
  icon: 'event',
  pkField: 'event_id',
  routePath: 'events',
  formMode: 'page',
  searchPlaceholder: 'Search by name or description...',
  activeLabel: 'Active',
  inactiveLabel: 'Closed',
  columns: [
    { field: 'event_name', header: 'Name', type: 'text', sortable: true },
    { field: 'event_type', header: 'Type', type: 'text', sortable: true },
    { field: 'start_date', header: 'Start Date', type: 'date', sortable: true },
    { field: 'current_phase', header: 'Phase', type: 'text', sortable: true, hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    { field: 'event_name', label: 'Event Name', type: 'text', required: true, maxLength: 60,
      group: 'Basic Information' },
    { field: 'event_type', label: 'Event Type', type: 'select', required: true,
      options: [
        { value: 'STORM', label: 'Storm' },
        { value: 'HURRICANE', label: 'Hurricane' },
        { value: 'TORNADO', label: 'Tornado' },
        { value: 'FLOOD', label: 'Flood' },
        { value: 'TSUNAMI', label: 'Tsunami' },
        { value: 'FIRE', label: 'Fire' },
        { value: 'EARTHQUAKE', label: 'Earthquake' },
        { value: 'WAR', label: 'War' },
        { value: 'EPIDEMIC', label: 'Epidemic' },
        { value: 'ADHOC', label: 'Ad Hoc' },
      ],
      group: 'Basic Information' },
    { field: 'start_date', label: 'Start Date', type: 'date', required: true,
      group: 'Basic Information' },
    { field: 'event_desc', label: 'Description', type: 'textarea', required: true, maxLength: 255, colspan: 2,
      group: 'Details' },
    { field: 'impact_desc', label: 'Impact Description', type: 'textarea', required: true, colspan: 2,
      group: 'Details' },

    { field: 'status_code', label: 'Status', type: 'select', required: true, defaultValue: 'A',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'C', label: 'Closed' },
      ],
      group: 'Status' },
    { field: 'closed_date', label: 'Closed Date', type: 'date',
      group: 'Status' },
    { field: 'reason_desc', label: 'Closure Reason', type: 'textarea', maxLength: 255,
      group: 'Status' },
  ],
};
