import { MasterTableConfig } from '../master-data.models';

export const IFRC_ITEM_REFERENCE_CONFIG: MasterTableConfig = {
  tableKey: 'ifrc_item_references',
  displayName: 'IFRC Item References',
  icon: 'qr_code_2',
  pkField: 'ifrc_item_ref_id',
  routePath: 'ifrc-item-references',
  formMode: 'page',
  formDescription:
    'An IFRC Item Reference is a specific product type within a family. ' +
    'Pick the IFRC Family and enter a description, then use "Suggest Reference Values" to auto-fill the codes. ' +
    'Adding size, form, or material improves the suggestion. Once saved, code fields are locked.',
  searchPlaceholder: 'Search by IFRC code, description, or spec attributes...',
  columns: [
    { field: 'ifrc_item_ref_id', header: 'ID', type: 'number', sortable: true, hideMobile: true },
    { field: 'ifrc_code', header: 'IFRC Code', type: 'text', sortable: true },
    { field: 'reference_desc', header: 'Reference Description', type: 'text', sortable: true },
    { field: 'category_label', header: 'Category Label', type: 'text', sortable: true, hideMobile: true },
    { field: 'spec_segment', header: 'Spec', type: 'text', sortable: true, hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    {
      field: 'ifrc_family_id',
      label: 'IFRC Family',
      type: 'lookup',
      required: true,
      lookupTable: 'ifrc_families',
      readonlyOnEdit: true,
      group: 'Start Here',
      hint: 'Which product family does this reference belong to? E.g. "Water Purification", "Grains and Cereals".',
      tooltip: 'Pick the family first — the suggest tool needs it to build the correct code prefix.',
    },
    {
      field: 'reference_desc',
      label: 'Reference Description',
      type: 'text',
      required: true,
      maxLength: 255,
      group: 'Start Here',
      hint: 'Plain description of the product. Up to 255 characters. E.g. "Water purification tablet, 500g", "Rice, white, long grain, 25kg bag".',
      tooltip: 'Enter this before suggesting — the tool reads the description to propose codes and categories.',
    },
    {
      field: 'size_weight',
      label: 'Size or Weight',
      type: 'text',
      maxLength: 40,
      uppercase: true,
      group: 'Product Attributes',
      hint: 'Optional. Up to 40 characters. E.g. 25 KG, 500 ML, 10 CM, 100 TABS.',
      tooltip: 'Helps the suggest tool tell apart similar products. Leave blank if size does not vary.',
    },
    {
      field: 'form',
      label: 'Form',
      type: 'text',
      maxLength: 40,
      uppercase: true,
      group: 'Product Attributes',
      hint: 'Optional. Up to 40 characters. E.g. TABLET, POWDER, LIQUID, BAG, KIT, BOTTLE, CANNED.',
      tooltip: 'Describes how the product is packaged or presented. Improves the suggested spec segment.',
    },
    {
      field: 'material',
      label: 'Material',
      type: 'text',
      maxLength: 40,
      uppercase: true,
      group: 'Product Attributes',
      hint: 'Optional. Up to 40 characters. E.g. COTTON, PLASTIC, CHLORINE, POLYESTER.',
      tooltip: 'Only needed when the material makes this product different from similar ones.',
    },
    {
      field: 'ifrc_code',
      label: 'IFRC Code',
      type: 'text',
      required: true,
      maxLength: 30,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Generated Codes',
      hint: 'The full product code. Up to 30 characters. E.g. FGRARICE01, WWTRTABL01. Auto-filled by suggestions.',
      tooltip: 'Locked after creation. Built from family + category + spec + sequence. Use "Create Replacement" if it needs to change.',
    },
    {
      field: 'category_code',
      label: 'Category Code',
      type: 'text',
      required: true,
      maxLength: 6,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Generated Codes',
      hint: 'Short product type within the family. Up to 6 characters. E.g. RICE, TABL, BLNK, TARP.',
      tooltip: 'Locked after creation. Auto-filled by the suggest tool based on the description.',
    },
    {
      field: 'category_label',
      label: 'Category Label',
      type: 'text',
      required: true,
      maxLength: 160,
      group: 'Generated Codes',
      hint: 'Readable name matching the category code. Up to 160 characters. E.g. "Rice", "Tablet", "Blanket".',
      tooltip: 'Can be edited after creation. Keep it consistent with the category code.',
    },
    {
      field: 'spec_segment',
      label: 'Spec Segment',
      type: 'text',
      maxLength: 7,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Generated Codes',
      hint: 'Short code that tells variants apart. Up to 7 characters. E.g. LG (long grain), TB (tablet), PW (powder).',
      tooltip: 'Locked after creation. Auto-filled from size, form, and material. Fill those fields first for better results.',
    },
    {
      field: 'source_version',
      label: 'Source Version',
      type: 'text',
      maxLength: 80,
      group: 'Details',
      hint: 'Optional. Up to 80 characters. E.g. "IFRC-2024-v3", "ODPEM-2025-Q1".',
      tooltip: 'Tracks which catalog version this entry came from. Leave blank if not applicable.',
    },
    {
      field: 'status_code',
      label: 'Status',
      type: 'select',
      required: true,
      defaultValue: 'A',
      group: 'Status',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      hint: 'Active references appear in item dropdowns. Set to Inactive to hide without deleting.',
      tooltip: 'Inactive records are kept for audit history. Items already linked to this reference are not affected.',
    },
  ],
};
