import { MasterTableConfig } from '../master-data.models';

export const IFRC_ITEM_REFERENCE_CONFIG: MasterTableConfig = {
  tableKey: 'ifrc_item_references',
  displayName: 'IFRC Item References',
  icon: 'qr_code_2',
  pkField: 'ifrc_item_ref_id',
  routePath: 'ifrc-item-references',
  formMode: 'dialog',
  formDescription:
    'IFRC Item References are Level 3 entries that represent specific product types within a family. ' +
    'When an item is linked to a reference, the IFRC Code becomes the item\'s canonical code. ' +
    'The category code + spec segment together with the family code form the full IFRC code. ' +
    'Size, form, and material are optional attributes that help users find the right match.',
  searchPlaceholder: 'Search by IFRC code, description, or spec attributes...',
  columns: [
    { field: 'ifrc_item_ref_id', header: 'ID', type: 'number', sortable: true, hideMobile: true },
    { field: 'ifrc_code', header: 'IFRC Code', type: 'text', sortable: true },
    { field: 'reference_desc', header: 'Reference Description', type: 'text', sortable: true },
    { field: 'category_label', header: 'Category Label', type: 'text', sortable: true, hideMobile: true },
    { field: 'spec_segment', header: 'Spec', type: 'text', sortable: true, hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    {
      field: 'ifrc_family_id',
      label: 'IFRC Family',
      type: 'lookup',
      required: true,
      lookupTable: 'ifrc_families',
      hint: 'The Level 2 family this reference belongs to. Must already exist under Catalogs > IFRC Families.',
    },
    {
      field: 'ifrc_code',
      label: 'IFRC Code',
      type: 'text',
      required: true,
      maxLength: 30,
      uppercase: true,
      hint: 'The full canonical code, e.g. "FGRARICE01". Built from: group code + family code + category code + spec segment.',
    },
    {
      field: 'reference_desc',
      label: 'Reference Description',
      type: 'text',
      required: true,
      maxLength: 255,
      hint: 'Human-readable product description shown to users. E.g. "Rice, white, long grain, 25 kg bag".',
    },
    {
      field: 'category_code',
      label: 'Reference Category Code',
      type: 'text',
      required: true,
      maxLength: 6,
      uppercase: true,
      hint: 'Short code for the product category within this family. E.g. "RICE", "TABL", "BLNK".',
    },
    {
      field: 'category_label',
      label: 'Reference Category Label',
      type: 'text',
      required: true,
      maxLength: 160,
      hint: 'Descriptive name for the category. E.g. "Rice", "Tablet", "Blanket".',
    },
    {
      field: 'spec_segment',
      label: 'Spec Segment',
      type: 'text',
      maxLength: 7,
      uppercase: true,
      hint: 'Optional 2-4 char code that distinguishes variants. E.g. "LG" (long grain), "TB" (tablet form).',
    },
    {
      field: 'size_weight',
      label: 'Size or Weight',
      type: 'text',
      maxLength: 40,
      uppercase: true,
      hint: 'Optional physical size or weight. E.g. "25 KG", "500 ML", "10 CM". Helps users match items.',
    },
    {
      field: 'form',
      label: 'Form',
      type: 'text',
      maxLength: 40,
      uppercase: true,
      hint: 'Optional presentation form. E.g. "TABLET", "LIQUID", "POWDER", "CANNED", "BAG".',
    },
    {
      field: 'material',
      label: 'Material',
      type: 'text',
      maxLength: 40,
      uppercase: true,
      hint: 'Optional material composition. E.g. "COTTON", "PLASTIC", "CHLORINE", "POLYESTER".',
    },
    {
      field: 'source_version',
      label: 'Source Version',
      type: 'text',
      maxLength: 80,
      hint: 'Optional. The IFRC catalog version this entry was sourced from (e.g. "IFRC-2024-v3").',
    },
    {
      field: 'status_code',
      label: 'Status',
      type: 'select',
      required: true,
      defaultValue: 'A',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      hint: 'Set to Inactive to hide from item classification dropdowns without deleting.',
    },
  ],
};
