import { MasterTableConfig } from '../master-data.models';

export const IFRC_ITEM_REFERENCE_CONFIG: MasterTableConfig = {
  tableKey: 'ifrc_item_references',
  displayName: 'IFRC Item References',
  icon: 'qr_code_2',
  pkField: 'ifrc_item_ref_id',
  routePath: 'ifrc-item-references',
  formMode: 'page',
  formDescription:
    'An IFRC Item Reference is a specific governed product type within a family. ' +
    'Pick the IFRC Family and enter a description, then use "Suggest Reference Values" to auto-fill the IFRC classification codes. ' +
    'The reference inherits its Level 1 category through the family. Size, form, and material improve classification, but they do not define the item\'s operational UOM.',
  searchPlaceholder: 'Search by IFRC code, description, or spec attributes...',
  columns: [
    { field: 'ifrc_item_ref_id', header: 'ID', type: 'number', sortable: true, hideMobile: true },
    { field: 'ifrc_code', header: 'IFRC Code', type: 'text', sortable: true },
    { field: 'reference_desc', header: 'Reference Description', type: 'text', sortable: true },
    { field: 'category_label', header: 'Category Label', type: 'text', sortable: true, hideMobile: true },
    { field: 'spec_segment', header: 'Spec', type: 'text', sortable: true, hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    {
      field: 'ifrc_family_id',
      label: 'IFRC Family',
      type: 'lookup',
      hint: 'IFRC family this reference belongs to; it controls valid category alignment.',
      required: true,
      lookupTable: 'ifrc_families',
      readonlyOnEdit: true,
      group: 'Start Here',
      tooltip: 'Pick the family first because it controls the code prefix and the Level 1 category this reference rolls up to.' },
    {
      field: 'reference_desc',
      label: 'Reference Description',
      type: 'text',
      hint: 'Product description item authors see when matching a local item to IFRC.',
      placeholder: 'Water purification tablets',
      required: true,
      maxLength: 255,
      group: 'Start Here',
      tooltip: 'Enter this before suggesting - the tool reads the description to propose codes and categories.' },
    {
      field: 'size_weight',
      label: 'Size or Weight',
      type: 'text',
      hint: 'Size, weight, or count that distinguishes this IFRC reference.',
      placeholder: '25 kg',
      maxLength: 40,
      uppercase: true,
      group: 'Product Attributes',
      tooltip: 'Helps the suggest tool tell apart similar products. Leave blank if size does not vary.' },
    {
      field: 'form',
      label: 'Form',
      type: 'text',
      hint: 'Physical form operators use to compare the reference with stock on hand.',
      placeholder: 'Tablet',
      maxLength: 40,
      uppercase: true,
      group: 'Product Attributes',
      tooltip: 'Classification attribute only. It improves the suggested IFRC spec segment, but it is not the same as the item master UOM.' },
    {
      field: 'material',
      label: 'Material',
      type: 'text',
      hint: 'Primary material when it affects storage, handling, or distribution.',
      placeholder: 'Cotton',
      maxLength: 40,
      uppercase: true,
      group: 'Product Attributes',
      tooltip: 'Only needed when the material makes this product different from similar ones.' },
    {
      field: 'ifrc_code',
      label: 'IFRC Code',
      type: 'text',
      hint: "Full IFRC product code used as the mapped item's canonical code.",
      placeholder: '(set on creation; locked once saved)',
      required: true,
      maxLength: 30,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Generated Codes',
      tooltip: 'Locked after creation. Built from family + category + spec + sequence. When an item maps to this reference, the item master uses this code canonically.' },
    {
      field: 'category_code',
      label: 'Category Code',
      type: 'text',
      hint: 'Short IFRC category code within the selected family.',
      placeholder: '(set on creation; locked once saved)',
      required: true,
      maxLength: 6,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Generated Codes',
      tooltip: 'Locked after creation. Auto-filled by the suggest tool based on the description.' },
    {
      field: 'category_label',
      label: 'Category Label',
      type: 'text',
      hint: 'Readable IFRC category name shown with the governed reference.',
      placeholder: 'Water treatment',
      required: true,
      maxLength: 160,
      group: 'Generated Codes',
      tooltip: 'Can be edited after creation. Keep it consistent with the IFRC category code used inside this family.' },
    {
      field: 'spec_segment',
      label: 'Spec Segment',
      type: 'text',
      hint: 'IFRC specification segment that completes the governed reference code.',
      placeholder: '(set on creation; locked once saved)',
      maxLength: 7,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Generated Codes',
      tooltip: 'Locked after creation. Auto-filled from size, form, and material. Fill those fields first for better results.' },
    {
      field: 'source_version',
      label: 'Source Version',
      type: 'text',
      hint: 'IFRC source release or import note used to trace this reference.',
      placeholder: 'IFRC-2024-v3',
      maxLength: 80,
      group: 'Details',
      tooltip: 'Tracks which catalog version this entry came from. Leave blank if not applicable.' },
    {
      field: 'status_code',
      label: 'Status',
      type: 'select',
      hint: 'Active references can map items; inactive references remain for existing catalog history.',
      required: true,
      defaultValue: 'A',
      group: 'Status',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      tooltip: 'Inactive records are kept for audit history. Items already linked to this reference are not affected.' },
  ],
};
