import { MasterTableConfig } from '../master-data.models';

export const IFRC_FAMILY_CONFIG: MasterTableConfig = {
  tableKey: 'ifrc_families',
  displayName: 'IFRC Families',
  icon: 'account_tree',
  pkField: 'ifrc_family_id',
  routePath: 'ifrc-families',
  formMode: 'page',
  formDescription:
    'An IFRC Family groups similar products together under a governed Level 1 category. ' +
    'Fill in the Family Label, then use "Suggest Family Values" to auto-fill the IFRC codes. ' +
    'Group label helps users read the taxonomy, but category alignment is governed at the family level. Once saved, codes are locked.',
  searchPlaceholder: 'Search by group, family code, or label...',
  columns: [
    { field: 'ifrc_family_id', header: 'ID', type: 'number', sortable: true, hideMobile: true },
    { field: 'group_code', header: 'Group Code', type: 'text', sortable: true },
    { field: 'group_label', header: 'Group Label', type: 'text', sortable: true, hideMobile: true },
    { field: 'family_code', header: 'Family Code', type: 'text', sortable: true },
    { field: 'family_label', header: 'Family Label', type: 'text', sortable: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    {
      field: 'family_label',
      label: 'Family Label',
      type: 'text',
      hint: 'Name item authors see when choosing the IFRC family for a product.',
      placeholder: 'Water Purification',
      required: true,
      maxLength: 160,
      group: 'Start Here',
      tooltip: 'Enter this first - the suggest tool uses it to generate codes automatically.' },
    {
      field: 'category_id',
      label: 'Level 1 Category',
      type: 'lookup',
      hint: 'Level 1 DMIS category this IFRC family supports for reporting and burn-rate fallback.',
      required: true,
      lookupTable: 'item_categories',
      group: 'Start Here',
      tooltip: 'Choose the approved business category for this family. Group label alone does not determine the Level 1 category.' },
    {
      field: 'group_code',
      label: 'Group Code',
      type: 'text',
      hint: 'Short IFRC group code used to build governed item references.',
      placeholder: '(set on creation; locked once saved)',
      required: true,
      maxLength: 4,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Codes',
      tooltip: 'Locked after creation. Use "Suggest Family Values" to auto-fill, or enter manually if you know the IFRC code.' },
    {
      field: 'family_code',
      label: 'Family Code',
      type: 'text',
      hint: 'Short family code used with the group code to identify this IFRC family.',
      placeholder: '(set on creation; locked once saved)',
      required: true,
      maxLength: 6,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Codes',
      tooltip: 'Locked after creation. This becomes part of every item code linked to this family.' },
    {
      field: 'group_label',
      label: 'Group Label',
      type: 'text',
      hint: 'Readable group name shown when catalog teams review IFRC classification.',
      placeholder: 'Food and Nutrition',
      required: true,
      maxLength: 120,
      group: 'Details',
      tooltip: 'Display label for the IFRC group. Useful for users, but Level 1 category is governed from the family-category mapping.' },
    {
      field: 'source_version',
      label: 'Source Version',
      type: 'text',
      hint: 'IFRC source release or import note used to trace this classification.',
      placeholder: 'IFRC-2024-v3',
      maxLength: 80,
      group: 'Details',
      tooltip: 'Tracks which catalog version this entry came from. Leave blank if not applicable.' },
    {
      field: 'status_code',
      label: 'Status',
      type: 'select',
      hint: 'Active families appear in item lookups; inactive families stay for existing mappings.',
      required: true,
      defaultValue: 'A',
      group: 'Status',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      tooltip: 'Inactive records are kept for audit history. Items already linked to this family are not affected.' },
  ],
};
