import { MasterTableConfig } from '../master-data.models';

export const IFRC_FAMILY_CONFIG: MasterTableConfig = {
  tableKey: 'ifrc_families',
  displayName: 'IFRC Families',
  icon: 'account_tree',
  pkField: 'ifrc_family_id',
  routePath: 'ifrc-families',
  formMode: 'page',
  formDescription:
    'An IFRC Family groups similar products together under a business category. ' +
    'Fill in the Family Label, then use "Suggest Family Values" to auto-fill the codes. ' +
    'Once saved, codes are locked. Use "Create Replacement" if a code needs to change.',
  searchPlaceholder: 'Search by group, family code, or label...',
  columns: [
    { field: 'ifrc_family_id', header: 'ID', type: 'number', sortable: true, hideMobile: true },
    { field: 'group_code', header: 'Group Code', type: 'text', sortable: true },
    { field: 'group_label', header: 'Group Label', type: 'text', sortable: true, hideMobile: true },
    { field: 'family_code', header: 'Family Code', type: 'text', sortable: true },
    { field: 'family_label', header: 'Family Label', type: 'text', sortable: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    {
      field: 'family_label',
      label: 'Family Label',
      type: 'text',
      required: true,
      maxLength: 160,
      group: 'Start Here',
      hint: 'The name users will see in dropdowns. Up to 160 characters. E.g. "Water Purification", "Grains and Cereals".',
      tooltip: 'Enter this first — the suggest tool uses it to generate codes automatically.',
    },
    {
      field: 'category_id',
      label: 'Level 1 Category',
      type: 'lookup',
      required: true,
      lookupTable: 'item_categories',
      group: 'Start Here',
      hint: 'Which business category does this family belong to? E.g. Medical Supplies, Food and Water.',
      tooltip: 'Setting this before suggesting helps narrow the results to the right branch.',
    },
    {
      field: 'group_code',
      label: 'Group Code',
      type: 'text',
      required: true,
      maxLength: 4,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Codes',
      hint: '1-4 letters. The broad product area. E.g. F (Food), W (Water), M (Medical), S (Shelter).',
      tooltip: 'Locked after creation. Use "Suggest Family Values" to auto-fill, or enter manually if you know the IFRC code.',
    },
    {
      field: 'family_code',
      label: 'Family Code',
      type: 'text',
      required: true,
      maxLength: 6,
      uppercase: true,
      readonlyOnEdit: true,
      group: 'Codes',
      hint: '1-6 letters. Identifies this family within the group. E.g. GRAIN, DAIRY, WTRPUR, TARP.',
      tooltip: 'Locked after creation. This becomes part of every item code linked to this family.',
    },
    {
      field: 'group_label',
      label: 'Group Label',
      type: 'text',
      required: true,
      maxLength: 120,
      group: 'Details',
      hint: 'Full name for the group. Up to 120 characters. E.g. "Food and Nutrition", "Water and Sanitation".',
      tooltip: 'Should match the Group Code. Can be updated after creation.',
    },
    {
      field: 'source_version',
      label: 'Source Version',
      type: 'text',
      maxLength: 80,
      group: 'Details',
      hint: 'Optional. Up to 80 characters. E.g. "IFRC-2024-v3", "ODPEM-2025-Q1".',
      tooltip: 'Tracks which catalog version this entry came from. Leave blank if not applicable.',
    },
    {
      field: 'status_code',
      label: 'Status',
      type: 'select',
      required: true,
      defaultValue: 'A',
      group: 'Status',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      hint: 'Active families appear in item dropdowns. Set to Inactive to hide without deleting.',
      tooltip: 'Inactive records are kept for audit history. Items already linked to this family are not affected.',
    },
  ],
};
