import { MasterTableConfig } from '../master-data.models';

export const ITEM_CATEGORY_CONFIG: MasterTableConfig = {
  tableKey: 'item_categories',
  displayName: 'Item Categories',
  icon: 'folder_open',
  pkField: 'category_id',
  routePath: 'item-categories',
  formMode: 'page',
  governanceNoteTitle: 'Why this matters',
  governanceNoteBody: 'This category is used for reporting and stock-planning rules. Items assigned here should match the approved business grouping.',
  governanceNoteCompact: true,
  searchPlaceholder: 'Search by code or description...',
  columns: [
    { field: 'category_id', header: 'ID', type: 'number', sortable: true, hideMobile: true },
    { field: 'category_code', header: 'Code', type: 'text', sortable: true },
    { field: 'category_desc', header: 'Description', type: 'text', sortable: true },
    { field: 'category_type', header: 'Type', type: 'text', sortable: true, hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    {
      field: 'category_code',
      label: 'Code',
      type: 'text',
      required: true,
      maxLength: 30,
      uppercase: true,
      group: 'Category Details',
      hint: 'Short uppercase code used across reports and integrations.',
      placeholder: 'e.g. FOOD, SHELTER, WASH',
      tooltip: 'Must be unique. Used in burn-rate fallbacks and stock-health dashboards. e.g. FOOD, SHELTER, WASH, MED',
    },
    {
      field: 'category_desc',
      label: 'Description',
      type: 'text',
      required: true,
      maxLength: 60,
      group: 'Category Details',
      hint: 'Human-readable name shown in dropdowns and reports.',
      placeholder: 'e.g. Food & Nutrition',
      tooltip: 'Full display name for this category. e.g. "Food & Nutrition", "Shelter & NFI", "Water, Sanitation & Hygiene"',
    },
    {
      field: 'category_type',
      label: 'Type',
      type: 'select',
      required: false,
      defaultValue: 'GOODS',
      options: [
        { value: 'GOODS', label: 'Goods' },
        { value: 'FUNDS', label: 'Funds' },
      ],
      group: 'Category Details',
      hint: 'Goods for physical items, Funds for monetary allocations.',
      tooltip: 'Most categories are Goods. Use Funds only for budget-tracked monetary categories.',
    },
    {
      field: 'comments_text',
      label: 'Comments',
      type: 'textarea',
      maxLength: 300,
      group: 'Notes',
      hint: 'Administrative notes or audit-relevant context.',
      tooltip: 'e.g. "Approved by ODPEM directive 2024-15" or "Maps to IFRC Product Group HFOO"',
    },
    {
      field: 'status_code',
      label: 'Status',
      type: 'select',
      required: true,
      defaultValue: 'A',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      group: 'Status',
    },
  ],
};
