import { MasterTableConfig } from '../master-data.models';

export const SUPPLIER_CONFIG: MasterTableConfig = {
  tableKey: 'suppliers',
  displayName: 'Suppliers',
  icon: 'local_shipping',
  pkField: 'supplier_id',
  routePath: 'suppliers',
  formMode: 'page',
  searchPlaceholder: 'Search by code, name, or contact...',
  columns: [
    { field: 'supplier_code', header: 'Code', type: 'text', sortable: true },
    { field: 'supplier_name', header: 'Name', type: 'text', sortable: true },
    { field: 'contact_name', header: 'Contact', type: 'text', sortable: true, hideMobile: true },
    { field: 'default_lead_time_days', header: 'Lead Time', type: 'number', sortable: true, hideMobile: true },
    { field: 'is_framework_supplier', header: 'Framework', type: 'boolean', hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    { field: 'supplier_code', label: 'Supplier Code', type: 'text', required: true, maxLength: 20, uppercase: true,
      hint: 'Short supplier key used on procurement records and reports.',
      placeholder: 'SUP-KGN-001',
      group: 'Basic Information' },
    { field: 'supplier_name', label: 'Supplier Name', type: 'text', required: true, maxLength: 120,
      hint: 'Registered supplier name procurement teams will see on orders.',
      placeholder: 'Kingston Relief Supplies Ltd.',
      group: 'Basic Information' },
    { field: 'trn_no', label: 'TRN', type: 'text', maxLength: 30,
      hint: 'Taxpayer Registration Number used for vendor compliance checks.',
      placeholder: '123-456-789',
      group: 'Basic Information' },
    { field: 'tcc_no', label: 'TCC', type: 'text', maxLength: 30,
      hint: 'Tax Compliance Certificate reference used before procurement award.',
      placeholder: 'TCC-2026-0412',
      group: 'Basic Information' },

    { field: 'contact_name', label: 'Contact Name', type: 'text', maxLength: 80,
      hint: 'Supplier contact who can confirm quotes, lead times, and delivery.',
      placeholder: 'Marcia Clarke',
      group: 'Contact' },
    { field: 'phone_no', label: 'Phone', type: 'phone', maxLength: 20,
      hint: 'Number procurement teams can call during ordering and delivery.',
      placeholder: '+1 876 555 0123',
      group: 'Contact' },
    { field: 'email_text', label: 'Email', type: 'email', maxLength: 100,
      hint: 'Email used for quotes, orders, and delivery follow-up.',
      placeholder: 'orders@supplier.example',
      group: 'Contact' },

    { field: 'address_text', label: 'Address', type: 'textarea', maxLength: 255,
      hint: 'Business or delivery address used for supplier records.',
      placeholder: '22 Marcus Garvey Drive, Kingston',
      group: 'Address' },
    { field: 'parish_code', label: 'Parish', type: 'lookup', lookupTable: 'parishes',
      hint: 'Parish used for local routing and supplier reporting.',
      group: 'Address' },
    { field: 'country_id', label: 'Country', type: 'lookup', lookupTable: 'countries',
      hint: 'Country this supplier is based in for procurement reporting.',
      group: 'Address' },

    { field: 'default_lead_time_days', label: 'Default Lead Time (days)', type: 'number', defaultValue: 14,
      hint: 'Typical days from order approval to delivery.',
      group: 'Procurement' },
    { field: 'is_framework_supplier', label: 'Framework Supplier', type: 'boolean', defaultValue: false,
      hint: 'ON means an approved framework contract exists; OFF uses normal sourcing.',
      group: 'Procurement' },
    { field: 'framework_contract_no', label: 'Framework Contract No.', type: 'text', maxLength: 50,
      hint: 'Framework contract reference used to buy quickly during response.',
      placeholder: 'FW-ODPEM-2026-07',
      group: 'Procurement' },
    { field: 'framework_expiry_date', label: 'Framework Expiry Date', type: 'date',
      hint: 'Date the framework contract stops being valid for procurement.',
      placeholder: '2026-12-31',
      group: 'Procurement' },

    { field: 'status_code', label: 'Status', type: 'select', required: true, defaultValue: 'A',
      hint: 'Active suppliers can be selected for procurement; inactive suppliers stay for history.',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      group: 'Status' },
  ],
};
