import { MasterTableConfig } from '../master-data.models';

const STATUS_TONES = [
  { value: 'A', label: 'Active', tone: 'success', icon: 'check_circle' },
  { value: 'I', label: 'Inactive', tone: 'neutral', icon: 'radio_button_unchecked' },
  { value: 'L', label: 'Locked', tone: 'critical', icon: 'lock' },
] as const;

export const USERS_CONFIG: MasterTableConfig = {
  tableKey: 'user',
  displayName: 'Users',
  icon: 'manage_accounts',
  pkField: 'user_id',
  routePath: 'users',
  domain: 'advanced',
  formMode: 'page',
  searchPlaceholder: 'Search by username, email, or full name',
  formDescription: 'Tenant is required for user creation. Legacy Agency is optional and used only for legacy workflows.',
  emptyState: {
    icon: 'person_off',
    title: 'No users yet',
    message: 'Users are auto-provisioned on first Keycloak login.',
    actionIcon: 'add',
    actionLabel: 'Add User',
  },
  columns: [
    { field: 'username', header: 'Username', type: 'text', sortable: true, monospace: true },
    { field: 'full_name', header: 'Full Name', type: 'text', sortable: true },
    { field: 'primary_tenant_label', header: 'Primary Tenant', type: 'text', hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true, toneMap: STATUS_TONES },
  ],
  formFields: [
    { field: 'username', label: 'Username', type: 'text', hint: 'Keycloak username used to match login to this DMIS user.', placeholder: '(set on creation; locked once saved)', required: true, maxLength: 60, readonlyOnEdit: true, group: 'Identity', colspan: 2 },
    { field: 'email', label: 'Email', type: 'email', hint: 'Email used for login identity, alerts, and administrator contact.', placeholder: 'kemar.brown@odpem.gov.jm', required: true, maxLength: 200, group: 'Identity', colspan: 2 },
    { field: 'first_name', label: 'First Name', type: 'text', hint: 'Given name shown in user directories and assignment history.', placeholder: 'Kemar', maxLength: 100, group: 'Identity' },
    { field: 'last_name', label: 'Last Name', type: 'text', hint: 'Family name shown in user directories and assignment history.', placeholder: 'Brown', maxLength: 100, group: 'Identity' },
    { field: 'full_name', label: 'Full Name', type: 'text', hint: 'Display name others see in approvals, assignments, and audit trails.', placeholder: 'Kemar Brown', maxLength: 200, group: 'Identity', colspan: 2 },
    { field: 'tenant_id', label: 'Tenant', type: 'lookup', lookupTable: 'tenant',
      hint: 'Required primary tenant membership created with this user.',
      required: true, createOnly: true, group: 'Operational', colspan: 2 },
    { field: 'assigned_warehouse_id', label: 'Assigned Warehouse', type: 'lookup', lookupTable: 'warehouses',
      hint: 'Warehouse this user manages or works from day to day.',
      group: 'Operational' },
    { field: 'agency_id', label: 'Legacy Agency (optional)', type: 'lookup',
      hint: 'Optional. Use only for legacy workflows that still depend on agency_id; tenant membership governs user access.',
      lookupTable: 'agencies', group: 'Operational' },
    { field: 'is_active', label: 'Active', type: 'boolean', hint: 'ON allows the account to operate in DMIS; OFF disables local access.', defaultValue: true, group: 'Operational' },
    { field: 'phone', label: 'Phone', type: 'phone', hint: 'Mobile number for surge alerts and operational follow-up.', placeholder: '+1 876 555 0123', maxLength: 50, group: 'Locale' },
    { field: 'timezone', label: 'Timezone', type: 'text', required: true, maxLength: 50,
      hint: 'Timezone used when displaying timestamps to this user.',
      placeholder: 'America/Jamaica',
      defaultValue: 'America/Jamaica', group: 'Locale' },
    { field: 'language', label: 'Language', type: 'text', required: true, maxLength: 10, defaultValue: 'en',
      hint: 'Preferred interface language code for this user.',
      placeholder: 'en',
      group: 'Locale' },
    { field: 'status_code', label: 'Status', type: 'select', required: true, defaultValue: 'A',
      hint: 'Active users can work; inactive users are retained; locked users cannot log in.',
      options: STATUS_TONES.map(({ value, label }) => ({ value, label })),
      valueHints: [{ value: 'L', hint: 'Locked accounts cannot log in. Reset password to unlock.' }],
      group: 'Status', editOnly: true },
  ],
};
