import { MasterTableConfig } from '../master-data.models';

export const WAREHOUSE_CONFIG: MasterTableConfig = {
  tableKey: 'warehouses',
  displayName: 'Warehouses',
  icon: 'warehouse',
  pkField: 'warehouse_id',
  routePath: 'warehouses',
  formMode: 'page',
  formDescription: 'Select the managing tenant responsible for stocking and operating this warehouse. Custodian remains legacy/transitional compatibility only.',
  searchPlaceholder: 'Search by name or contact...',
  columns: [
    { field: 'warehouse_name', header: 'Name', type: 'text', sortable: true },
    { field: 'warehouse_type', header: 'Type', type: 'text', sortable: true },
    { field: 'managing_tenant_label', header: 'Managing Tenant', type: 'text', hideMobile: true },
    { field: 'parish_code', header: 'Parish', type: 'text', sortable: true, hideMobile: true },
    { field: 'contact_name', header: 'Contact', type: 'text', sortable: true, hideMobile: true },
    { field: 'phone_no', header: 'Phone', type: 'text', hideMobile: true },
    { field: 'status_code', header: 'Status', type: 'status', sortable: true },
  ],
  formFields: [
    { field: 'warehouse_name', label: 'Warehouse Name', type: 'text', required: true, maxLength: 255,
      hint: 'Name responders and inventory teams see when choosing a stock hub.',
      placeholder: 'Kingston Main Warehouse',
      group: 'Basic Information' },
    { field: 'warehouse_type', label: 'Type', type: 'select', required: true,
      hint: 'Identifies whether this hub is a main hub or sub-hub for routing.',
      options: [
        { value: 'MAIN-HUB', label: 'Main Hub' },
        { value: 'SUB-HUB', label: 'Sub Hub' },
      ],
      group: 'Basic Information' },
    { field: 'tenant_id', label: 'Managing Tenant', type: 'lookup', required: true, lookupTable: 'tenant',
      hint: 'Authoritative tenant responsible for managing, stocking, and operating this warehouse.',
      group: 'Basic Information' },
    { field: 'min_stock_threshold', label: 'Min Stock Threshold', type: 'number', defaultValue: 0,
      hint: 'Floor that flags warehouse stock as needing attention.',
      group: 'Basic Information' },

    { field: 'address1_text', label: 'Address Line 1', type: 'text', required: true, maxLength: 255,
      hint: 'Primary address drivers and field teams use to reach this warehouse.',
      placeholder: '12 Camp Road, Kingston',
      group: 'Address' },
    { field: 'address2_text', label: 'Address Line 2', type: 'text', maxLength: 255,
      hint: 'Additional address detail such as gate, building, or landmark.',
      placeholder: 'Gate 2, rear loading bay',
      group: 'Address' },
    { field: 'parish_code', label: 'Parish', type: 'lookup', required: true, lookupTable: 'parishes',
      hint: 'Parish used for routing, reporting, and field coordination.',
      group: 'Address' },

    { field: 'contact_name', label: 'Contact Name', type: 'text', required: true, maxLength: 50, uppercase: true,
      hint: 'Person teams should call before pickup, delivery, or inspection.',
      placeholder: 'Kemar Brown',
      group: 'Contact' },
    { field: 'phone_no', label: 'Phone', type: 'phone', required: true, maxLength: 20,
      hint: 'Number field teams can call during operations.',
      placeholder: '+1 876 555 0123',
      pattern: '^\\+1 \\(\\d{3}\\) \\d{3}-\\d{4}$', patternMessage: 'Format: +1 (XXX) XXX-XXXX',
      group: 'Contact' },
    { field: 'email_text', label: 'Email', type: 'email', maxLength: 100,
      hint: 'Email used for warehouse confirmations and follow-up.',
      placeholder: 'warehouse@odpem.gov.jm',
      group: 'Contact' },

    { field: 'status_code', label: 'Status', type: 'select', required: true, defaultValue: 'A',
      hint: 'Active warehouses can hold and dispatch stock; inactive warehouses stay for history.',
      options: [
        { value: 'A', label: 'Active' },
        { value: 'I', label: 'Inactive' },
      ],
      group: 'Status' },
    { field: 'reason_desc', label: 'Reason', type: 'textarea', maxLength: 255,
      hint: 'Reason for a status or governance change reviewers may need later.',
      placeholder: 'Closed for roof repair after inspection',
      group: 'Status' },
  ],
};
